### ISSUE TITLE
Missing flow-over-heated-plate with CalculiX

### ISSUE THREAD

**Issue by Alphaoo1** [precice/tutorials#103]
Currently, CHT tutorials for OpenFOAM+FENICS, OpenFOAM+NUTILS and OpenFOAM+Aster are available.
Although, a tutorial case for OpenFOAM+CalculiX CHT is available, it is currently not working for me due to [issue](https://precice.discourse.group/t/openfoam-calculix-heat-exchanger-cht-tutorial-does-not-run/312) mentioned on discourse.

Also, it would be nice to have a simple case as compared to the heat-exchanger problem.

Thank you.

**Comment by uekerman** [comment]
Yes, we should add the "flow over heated plate" also for OpenFOAM + CalculiX.
