### ISSUE TITLE
Add an implicit multi-coupling tutorial

### ISSUE THREAD

**Issue by uekerman** [precice/tutorials#106]
`couping-scheme:multi` is a rather complicated feature of preCICE for which we currently over no real example. [Documentation entry](https://github.com/precice/precice/wiki/Multi-Coupling-Configuration#fully-implicit-multi-coupling). 
To create one could be simple though: A channel flow with two flaps or two channel flows separated by an elastic membrane would do the job.
Could also be a nice addition to the system tests.

**Comment by MakisH** [comment]
This was added with #110.
