### ISSUE TITLE
Mesh FSI/OpenFOAM-FEniCS inconsistent with other tutorials

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#108]
I just noticed that in almost all the "flap_perp" cases we have a geometry/mesh with width 0.3m:
https://github.com/precice/tutorials/blob/95cc1ed1294c9c9e5af4d6bcc6393be4cd8dcb53/FSI/flap_perp/OpenFOAM-CalculiX/Fluid/system/blockMeshDict#L21

while in OpenFOAM-FEniCS (only) we have width 1m:
https://github.com/precice/tutorials/blob/95cc1ed1294c9c9e5af4d6bcc6393be4cd8dcb53/FSI/flap_perp/OpenFOAM-FEniCS/Fluid/system/blockMeshDict#L21-L22

@richahert was there a particular reason for this choice?

**Comment by BenjaminRodenberg** [comment]
I assume that this has something to do with the 2D/3D vs. 3D/3D coupling. @IshaanDesai updated this recently. 

OpenFOAM-FEniCS is truly 2D now: https://github.com/precice/tutorials/tree/master/FSI/flap_perp_2D
OpenFOAM-CalculiX is 3D now: https://github.com/precice/tutorials/tree/master/FSI/flap_perp

Does this resolve the issue?

**Comment by IshaanDesai** [comment]
> Does this resolve the issue?

I just noticed that in the FEniCS setup the flap width is:
https://github.com/precice/tutorials/blob/5f4031fc7e45807dca787a525569b39a1909d2a3/FSI/flap_perp_2D/OpenFOAM-FEniCS/Solid/perp-flap.py#L28

but in the OpenFOAM setup the flap width is:
https://github.com/precice/tutorials/blob/5f4031fc7e45807dca787a525569b39a1909d2a3/FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/system/blockMeshDict#L21-L22

As the case is purely 2D there is no reason for this inconsistency.

**Comment by BenjaminRodenberg** [comment]
> > Does this resolve the issue?
> 
> I just noticed that in the FEniCS setup the flap width is:
> 
> https://github.com/precice/tutorials/blob/5f4031fc7e45807dca787a525569b39a1909d2a3/FSI/flap_perp_2D/OpenFOAM-FEniCS/Solid/perp-flap.py#L28
> 
> but in the OpenFOAM setup the flap width is:
> 
> https://github.com/precice/tutorials/blob/5f4031fc7e45807dca787a525569b39a1909d2a3/FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/system/blockMeshDict#L21-L22
> 
> As the case is purely 2D there is no reason for this inconsistency.

This looks ok to me: `W` is the width (= y-direction) of the beam. In OpenFOAM we just have the center of the beam as reference. But as long as `w_f - w_b = W` everything is ok.

The inconsistency between OF-CCX and OF-FEniCS is still there. For OF-CCX we have a "thin" bar with only `0.3` width and in OF-FEniCS we have a "thick" bar with `1.0` width. We mainly have to agree on one of the two cases. I will now check whether the OF-FEniCS case also runs when using a "thin" bar.

**Comment by BenjaminRodenberg** [comment]
@richahert describes the case in his thesis: https://mediatum.ub.tum.de/doc/1520579/1520579.pdf

Figure 5.1 and Table 5.1 show all the measurements in the X-Y-plane:

![Screenshot from 2021-01-23 18-27-27](https://user-images.githubusercontent.com/5740604/105609315-b9524e80-5da8-11eb-8d8b-d445e78b9197.png)

Here, I think that all our tutorial cases agree. However, the "hidden" Z-dimension is sometimes `w=0.3`, sometimes `w_f=-0.5` and `w_b=0.5`.

**Comment by BenjaminRodenberg** [comment]
Looking through a few different combinations of solvers I found two possibilities `w=1.0` (used in `perp_flap_2D`) and `w=0.3` (used in `perp_flap`). I will provide a list with examples below.

### `flap_perp/OpenFOAM-Calculix` uses `0.3`

https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp/OpenFOAM-CalculiX/Fluid/system/blockMeshDict#L21

### `flap_perp/OpenFOAM-deal.II` uses `0.3`

https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp/OpenFOAM-deal.II/Fluid/system/blockMeshDict#L38-L49

### `flap_perp/SU2-CalculiX` uses `0.3` (?)

I cannot really "read" `su2` mesh files, but it is a 3D case

https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp/SU2-CalculiX/Fluid/fluidMesh.su2#L1

and I see quite some `0.3`s here and not many `1`s. (`CTRL+F` for ` 0.3 ` or ` 1 `; don't forget the spaces around the number).

https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp/SU2-CalculiX/Fluid/fluidMesh.su2#L259

### `flap_perp_2D/OpenFOAM-FEniCS` uses `1.0`

https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp_2D/OpenFOAM-FEniCS/Fluid/system/blockMeshDict#L21-L22

### `flap_perp_2D/OpenFOAM-deal.II` uses `1.0`

https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp_2D/OpenFOAM-deal.II/Fluid/system/blockMeshDict#L37-L48

### `flap_perp_2D/SU2-FEniCS` uses `1.0`

Actually it is a 2D case:

https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp_2D/SU2-FEniCS/Fluid/fluidMesh.su2#L1

Note: If we want `flap_perp_2D/SU2-FEniCS` and `flap_perp_2D/OpenFOAM-FEniCS` to produce matching results, we need `1.0` in `flap_perp_2D/OpenFOAM-FEniCS`. @IshaanDesai please correct me/edit this, if I'm wrong.

**Comment by BenjaminRodenberg** [comment]
# Do we want to resolve this inconsistency?

If we really want to resolve this inconsistency, I think we should use `w=1.0` for all cases, since this is much more natural. Or is there a real reason to use `0.3` for 3D cases? Additionally `w=1.0` does not require us to apply any scaling, if a 2D-3D coupling is required according to @IshaanDesai.

If the 3D cases really need `w=0.3` I would suggest to not resolve this inconsistency, since I think it is totally valid to use `w=1.0` for 2D cases (see argument above) and `w=0.3` for 3D cases (if there is a reason).

**Comment by IshaanDesai** [comment]
> Do we want to resolve this inconsistency?

This inconsistency needs to be resolved and `w=1.0` seems to be logical choice. The tutorials restructuring appears to have `dimension = 2` [in all cases](https://github.com/DavidSCN/tutorials/blob/restructure-flap/perpendicular-flap/precice-config.xml#L10) and hence having a width of `1.0` in the dead direction is favourable.

**Comment by MakisH** [comment]
I think a better factor to check here is the shape of the cells at the interface. In general, we don't want to end up with too thin cells, so `w=0.3` or similar may be a better option. @IshaanDesai maybe check how the meshes look like with different widths?

**Comment by BenjaminRodenberg** [comment]
In #146 Nutils and SU2 are 2D. OpenFOAM uses `w=1.0` (see [here](https://github.com/DavidSCN/tutorials/blob/af4cbce49567a593a621dda9173da8f694415456/perpendicular-flap/fluid-openfoam/system/blockMeshDict#L19-L47)). From my perspective merging #146 would therefore close this issue.

**Comment by IshaanDesai** [comment]
As per above comment, this is resolved in https://github.com/precice/tutorials/pull/146
