### ISSUE TITLE
Add tutorial template

### ISSUE THREAD

**Issue by uekerman** [precice/tutorials#111]
It could be helpful to have a tutorials template to copy from for new tutorials. 
For contributors as they then have to do less. 
For maintainers as contributors are nudged towards consistency. 

Such a template could include:
* a `README.md` with things are readme should / could include
* an `INSTRUCTIONS.md` with all you have to do if you contribute a tutorial. The contributor should finally delete this file
* a `precice-config.xml` with some different variants in there. Whatever you don't need, you can delete
* an `Allclean` script, if there is no global one?
* a `gitignore` if there is no global one
* an `Allrun` script with different options in there again  

Could be placed directly on the top level.
```
* CHT
* FSI
* template
```

Opinions on this?

**Comment by MakisH** [comment]
I definitely aggree that we need this!

Regarding `Allclean` and `.gitignore`, see also the related issues #88 and #87, respectively.

Regarding the location, top-level is good. Related issue there: #28.

**Comment by IshaanDesai** [comment]
If `Allrun` and `Allclean` scripts are provided in the template would it be assumed that the folder structure is also part of the template? The folder structure itself can be finalised then.
A possible far-future concern would be: when we have tutorials with more than two participants and with participants other than `Fluid/` and `Solid/`. At that point the template can be generalized further.

**Comment by MakisH** [comment]
We already have tutorials with more than two participants (and often special steps), so I am not so sure about `Allrun`. But `Allclean` we can write in a rather general way.

**Comment by MakisH** [comment]
Let's not add a template, only extensive contributing guidelines.
