### ISSUE TITLE
Restructure pseudo-2D cases to use preCICE in 2D

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#112]
We are currently defining a few tutorial cases (more prominently the [FSI/flap_perp](https://github.com/precice/tutorials/tree/master/FSI/flap_perp)) in the following way:
- the solver meshes are 3D, providing a fake additional layer in one direction, and
- the preCICE solver interface is defined as 3D (in the `precice-config.xml`).

After a series of cases that the RBF mapping fails on different systems (see https://github.com/precice/calculix-adapter/issues/37, https://github.com/precice/calculix-adapter/issues/43), @uekerman suggested that these cases are ill-defined and it is a coincidence that they succeed in some systems.

The reason that we were using 3D solver interfaces until now was that some adapters could not handle 2D meshes & data. Since https://github.com/precice/openfoam-adapter/pull/96, the OpenFOAM adapter can automatically work in a "2D coupling mode" and a nice example case is [deal.II-OpenFOAM (2D variant)](https://github.com/precice/tutorials/tree/master/FSI/flap_perp_2D/OpenFOAM-deal.II).

If we had the same functionality for CalculiX, FEniCS, and SU2, we could restructure the pseudo-2D cases to actually use 2D solver interfaces, even if the solvers themselves keep working in 3D internally. Maybe @KyleDavisSA and @IshaanDesai know more on how to implement this in these adapters.

**Comment by uekerman** [comment]
Problem is that the RBF mapping is ill-defined. If we have a case where a 2D mesh is extruded by one layer in span-wise direction, there is, first, not a lot of information to build up an interpolant in span-wise direction. Depending on how the layers on both sides look like this can lead to a ill-conditioned problem. If we mark the span-wise direction dead, though, we get duplicated rows in the RBF system matrix ... so a singular matrix. The QR decomposition directly detects this. If we use GMRES it could still converge if the right-hand side also has identical entries. If those differ, however (system-dependent differences of the order of machine precision might be enough), then also GMRES fails. 
The features "marking axis dead" is not meant for such situations. It is only meant for a single layer of cells that is parallel to an axis.


> If we had the same functionality for CalculiX, FEniCS, and SU2, we could restructure the pseudo-2D cases to actually use 2D solver interfaces, even if the solvers themselves keep working in 3D internally. Maybe @KyleDavisSA and @IshaanDesai know more on how to implement this in these adapters.

Actually, we only have to implement this for CalculiX (https://github.com/precice/calculix-adapter/issues/44). FEniCS and SU2 can do 2D simulations. That's what we should do here. And we already have 2D setups for that (https://github.com/precice/tutorials/pull/91).

I suggest to merge `flap_perp` and `flap_perp_2D` (that difference was anyway strange, same for cylinderFlap):
* Every solver should run in 2D if available (it is a 2D scenario). (SU2, FEniCS, deal.II, Nutils, ...)
* If a solver only offers 3D (OpenFOAM and CalculiX), they should use the internal 3D-2D mapping.

Remarks:
* Of course, things are different for real 3D cases, such as the 3D tube.
* We might need to do a similar thing for the CHT cases as well.

Tricky thing, we need to agree on: which dimension is the span-wise direction. More natural choice is probably the z-coordinate, but that means that we have to alter some of our tutorial meshes. 

In the long run, it would be beneficial to handle these mappings within preCICE:

```xml
<solver-interface dimensions="2">

    <participant name="OpenFOAM" dimensions="3">
        ...
    </participant>

    <participant name="FEniCS" dimensions="2">
      ...
    </participant>
```

**Comment by MakisH** [comment]
> Tricky thing, we need to agree on: which dimension is the span-wise direction. More natural choice is probably the z-coordinate, but that means that we have to alter some of our tutorial meshes.

Here we have already agreed that the perpendicular flap scenario is the inconsistent one and we want to rotate it (#34). So the z-coordinate is an easy choice.

**Comment by IshaanDesai** [comment]
This restructuring provides much needed clarity for the tutorials and also in general the handling of pseudo-2D-3D cases. One important point is that we are now changing the strategy for pseudo-2D-3D coupling: 
* Earlier we were converting the 2D adapters (FEniCS (already done) and SU2 (in process)) to handle 3D cases. In this approach the 2D adapter reads 3D data from preCICE and ignores one direction. The 3D participant solves a 3D case. 
* In the new approach the 2D adapters read 2D data from preCICE process to solve a standard 2D case. The 3D participant solves a 3D problem and writes 2D data to preCICE by ignoring one direction. **Modification (ignoring one direction) of data is now done before writing data to preCICE on the 3D side of the coupling**.

The new recommended approach is clear and straightforward. 

Upvote on Z-direction to be made the standard direction to be ignored.

**Comment by DavidSCN** [comment]
@MakisH I think we can close this issue, since #146 has addressed most of the issues. IIRC there is only one CalculiX topic left which deals with CHT (cell faces) in 2D.
