### ISSUE TITLE
Failure: FSI/flap_perp_2D/OpenFOAM-FEniCS

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/tutorials#131]
I just ran into an error, when trying to run `FSI/flap_perp/OpenFOAM-FEniCS` using the current state of develop (b74fdffb8062d6fd49733244be0d918643ec543c). Everything works for 13f101bb77461ea3f31451e3d22e6d72320c9f3e (before merging precice/fenics-adapter#71).

I used the following revision of the tutorial: https://github.com/precice/tutorials/pull/124/commits/ac6a94c6ae69b4dc7d4f6dd089ba57704e74bc35 (latest commit of https://github.com/precice/tutorials/pull/124). Observed the same behavior for https://github.com/precice/tutorials/commit/1c891a7882ddf3a2abdfa50ecafb941f1395eebb (latest commit of https://github.com/precice/tutorials/tree/develop).

**Comment by IshaanDesai** [comment]
@MakisH need your perspective on this error. The conclusion is that nothing is wrong on the FEniCS side. Is this a reasonable assumption?

**Comment by MakisH** [comment]
I see that it does solve a few iterations. How do the intermediate results look like visually? I guess that it either computes wrong forces or it receives wrong displacements.

@IshaanDesai would it also be easy for you to try with OpenFOAM v2006 and the adapter `develop` and document if you get the same error?

**Comment by IshaanDesai** [comment]
> I see that it does solve a few iterations. How do the intermediate results look like visually?

![Screenshot from 2020-12-22 15-28-45](https://user-images.githubusercontent.com/44898158/102898919-81cf4a00-446a-11eb-8ad9-c492a7be619e.png)

This is the fluid domain just before the crash, it looks reasonable.

> @IshaanDesai would it also be easy for you to try with OpenFOAM v2006 and the adapter `develop` and document if you get the same error? Do you get any error with OpenFOAM 7 and any other FSI tutorial?

I checked with OpenFOAM v2006 and the latest `develop` branch of the adapter and sadly the error is the same and it occurs slightly sooner than the error with OpenFOAM 7. The error log is similar:
```
---[precice]  it 2 of 50 | dt# 43 | t 0.42 of 5 | dt 0.01 | max dt 0.01 | ongoing yes | dt complete no | read-iteration-checkpoint | 
---[preciceAdapter] [DEBUG] Reading a checkpoint...
---[preciceAdapter] [DEBUG] Reloaded time value t = 0.420000
---[preciceAdapter] [DEBUG] Moving mesh points to their previous locations...
---[preciceAdapter] [DEBUG] Moved mesh points to their previous locations.
---[preciceAdapter] [DEBUG] Reading a mesh checkpoint...
---[preciceAdapter] [DEBUG] Mesh checkpoint was read. Time = 0.420000
---[preciceAdapter] [DEBUG] Checkpoint was read. Time = 0.420000
---[preciceAdapter] [DEBUG] Reading coupling data...
---[preciceAdapter] [DEBUG] Adjusting the solver's timestep...
---[preciceAdapter] [DEBUG] The solver's timestep is the same as the coupling timestep.
Courant Number mean: 1.42724 max: 16.6107
Time = 0.43

PIMPLE: iteration 1
smoothSolver:  Solving for cellDisplacementx, Initial residual = 0.998497, Final residual = 1.4967e-18, No Iterations 2
smoothSolver:  Solving for cellDisplacementy, Initial residual = 0.998802, Final residual = 8.10127e-18, No Iterations 2
DICPCG:  Solving for pcorr, Initial residual = 1, Final residual = 0.000880973, No Iterations 69
DICPCG:  Solving for pcorr, Initial residual = 0.515516, Final residual = 6.5027e-09, No Iterations 96
time step continuity errors : sum local = -8.16676e-08, global = -9.24857e-09, cumulative = 0.022902
#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::sigFpe::sigHandler(int) at ??:?
#2  ? in /lib/x86_64-linux-gnu/libpthread.so.0
#3  Foam::smoothSolver::solve(Foam::Field<double>&, Foam::Field<double> const&, unsigned char) const at ??:?
#4  Foam::fvMatrix<Foam::Vector<double> >::solveSegregated(Foam::dictionary const&) at ??:?
#5  Foam::fvMatrix<Foam::Vector<double> >::solveSegregatedOrCoupled(Foam::dictionary const&) at ??:?
#6  Foam::fvMesh::solve(Foam::fvMatrix<Foam::Vector<double> >&, Foam::dictionary const&) const at ??:?
#7  ? in /usr/lib/openfoam/openfoam2006/platforms/linux64GccDPInt32Opt/bin/pimpleFoam
#8  __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
#9  ? in /usr/lib/openfoam/openfoam2006/platforms/linux64GccDPInt32Opt/bin/pimpleFoam
./runFluid: line 44:  6207 Floating point exception(core dumped) $solver -case Fluid
Looking for any time directories without results (e.g. stray functionObjectProperties files, see issue #26 on GitHub)...
```

**Comment by IshaanDesai** [comment]
The above mentioned error does not occur when the case is run with a previous version of the `fenics-adapter`: https://github.com/precice/fenics-adapter/commit/d5517625598aec3a896995e3ba49f4df3fa76ee0.
This clearly means something went wrong in the redesigning of the FEniCS-Adapter: https://github.com/precice/fenics-adapter/pull/71

**Comment by IshaanDesai** [comment]
This issue is resolved with: https://github.com/precice/fenics-adapter/pull/111

**Comment by IshaanDesai** [comment]
This failure was traced down to a bug in the FEniCS-Adapter which was resolved in: https://github.com/precice/fenics-adapter/pull/111.
The tip displacement plot is now identical to the original result:
![tipdispl_OF-FE](https://user-images.githubusercontent.com/44898158/103487954-412be500-4e09-11eb-91d8-322e4dc8268a.png)
