### ISSUE TITLE
Create generic clean script

### ISSUE THREAD

**Issue by uekerman** [precice/tutorials#133]
As part of the [tutorial restructuring](https://github.com/orgs/precice/projects/5), we also want to change how cleaning works.
Currently, every tutorial case has its own `Allclean` script located at the root of the case. This leads to a lot of code duplication.
What we could do instead:

* Solver-specific cleaning scripts under `tools`:
```
- clean-openfoam.sh
- clean-calculix.sh
- ...
```
* A `clean.sh` per case, which calls the necessary solver-specific cleaning script. Maybe we need to pass the participant's name as an argument for this.
* Cleaning of preCICE-specific things (run folder, log files) could also be outsources to a `tools/clean-precice`.

**Comment by MakisH** [comment]
There is a question on whether this script should clean everything or only a specific case. I propose we follow the approach of `git clean`: we clean everything that is in the current directory and all children.

On how to start it:
- For users, recommend just calling it as `../../tools/clean.sh` to clean one participant, `../tools/clean.sh` to clean all participants, `tools/clean.sh` to clean all the cases.
- For advanced users, recommend adding it in their `PATH`.
