### ISSUE TITLE
Port 1D elastic tube to tutorials 

### ISSUE THREAD

**Issue by uekerman** [precice/tutorials#139]
As part of the [tutorials restructuring](https://github.com/orgs/precice/projects/5), we want to port the 1D elastic tube to the tutorials repo (and deprecate the current one).

There is already an empty target folder: https://github.com/precice/tutorials/tree/restructure/elastic-tube-1d

What we need is this structure: 
```
- images/
- fluid-cpp
- solid-cpp
- fluid-python
- solid-python
- precice-config.xml
- clean.sh
- README.md
```

An arbitrary combination of the cpp and the Python case should be possible.

For further conventions please copy from the `turek-hron-fsi3` structure: https://github.com/precice/tutorials/tree/restructure/turek-hron-fsi3

**Comment by MakisH** [comment]
Closed with #184
