### ISSUE TITLE
Add complex geometry fenics-fenics tutorial

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/tutorials#147]
In #137 we decided to temporarily remove the complex geometry case. As soon as #125 is merged, we want to add it again. Here some todos/reminders:

* How do we want to call the case? `partitioned-heat-conduction-complex`?
* I copied the latest version from `develop` (05a0a44) into the new structure defined in #125 at 8107fbb768f8b6e94d5ca916f9f59243280ee23b on the branch [`i_147`](https://github.com/precice/tutorials/tree/i_147).

**Comment by uekerman** [comment]
> partitioned-heat-conduction-complex

sounds good to me. The "complex" not only means the geometry, but also different data mapping, time-dependent BCs etc.

**Comment by BenjaminRodenberg** [comment]
I'll add a short specification similar to the one in #148 here, as well:

* Uses complex geometry (Circle + Plate with hole)
* Allows to swap Dirichlet and Neumann participants
* Uses Nearest Projection
* Allows to create non-matching meshes (with nearest neighbor this should still give us the exact solution, but I am not 100% sure)
* No subcycling (since this currently breaks the exact solution)
* Supports parallel runs.
* Supports time dependent flux & rhs (via parameter `gamma`)

Am I forgetting something here?

**Comment by BenjaminRodenberg** [comment]
I decided to put the complex geometry case directly into #137, since it was simple enough to do everything in one single iteration. This allows us to close this issue as soon as #137 (and #125) is merged.

**Comment by IshaanDesai** [comment]
> I decided to put the complex geometry case directly into #148, since it was simple enough to do everything in one single iteration. This allows us to close this issue as soon as #148 (and #125) is merged.

As per this comment all relevant PRs are merged and this issue is now resolved
