### ISSUE TITLE
Material properties of solid not consistent for all FSI perp_flap cases.

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/tutorials#150]
I did a quick survey on the material properties for the different FSI perp_flap cases that we offer:

**Important!** Table below is currently outdated.

| Case | flow type | Young's modulus (E) | Poisson's ratio (nu) | shear modulus (G, mu) | Lame's first parameter (lambda)|
|---------|---------------------------|----|---|---|---|
| `flap_perp/OpenFOAM-CalculiX` | incompressible | [400000](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp/OpenFOAM-CalculiX/Solid/flap.inp#L6) | [0.3](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp/OpenFOAM-CalculiX/Solid/flap.inp#L6)  | 153846* | 230769* |
| `flap_perp/OpenFOAM-deal.II`, linear | incompressible | ???  | ???| [153846](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp/OpenFOAM-deal.II/Solid/linear_elasticity.prm#L26-L27) | [230769](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp/OpenFOAM-deal.II/Solid/linear_elasticity.prm#L29-L30)
| `flap_perp/OpenFOAM-deal.II`, non-linear| incompressible |  ??? | [0.375](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp/OpenFOAM-deal.II/Solid/nonlinear_elasticity.prm#L28-L29)|[153846](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp/OpenFOAM-deal.II/Solid/nonlinear_elasticity.prm#L31-L32)|???|
| `flap_perp/SU2-CalculiX` | compressible | [200000](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp/SU2-CalculiX/Solid/flap.inp#L6)  | [0.3](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp/SU2-CalculiX/Solid/flap.inp#L6)|???|???|
| `flap_perp_2D/OpenFOAM-FEniCS` | incompressible | [400000](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp_2D/OpenFOAM-FEniCS/Solid/perp-flap.py#L30) | [0.3](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp_2D/OpenFOAM-FEniCS/Solid/perp-flap.py#L31) | ??? | ??? |
| `flap_perp_2D/OpenFOAM-deal.II`, linear | incompressible | ??? | ??? | [153846](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp_2D/OpenFOAM-deal.II/Solid/linear_elasticity.prm#L26-L27)| [230769](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp_2D/OpenFOAM-deal.II/Solid/linear_elasticity.prm#L29-L30) |
| `flap_perp_2D/OpenFOAM-deal.II`, non-linear | incompressible | ??? | [0.375](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp_2D/OpenFOAM-deal.II/Solid/nonlinear_elasticity.prm#L28-L29) | [153846](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp_2D/OpenFOAM-deal.II/Solid/nonlinear_elasticity.prm#L31-L32) | ??? |
| `flap_perp_2D/SU2-FEniCS` | compressible | [1000000](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp_2D/SU2-FEniCS/Solid/perp-flap.py#L30) | [0.3](https://github.com/precice/tutorials/blob/05a0a44cadd975a7dbf9cad5cd3eb9201c969b6a/FSI/flap_perp_2D/SU2-FEniCS/Solid/perp-flap.py#L31) | ??? | ??? |

Note: There is a nice table for conversion of these parameters on [wikipedia at the bottom of the entry](https://en.wikipedia.org/wiki/Poisson%27s_ratio). I used the formulas given on wikipedia for computing the numbers marked with a *.

**Comment by BenjaminRodenberg** [comment]
Some information that I've already got:

* @DavidSCN told me that the `0.375` for nu is an error. This will be fixed in #125 
* @IshaanDesai told me that for compressible flow E=400000 leads to instabilities. Therefore E=1000000 is used. **Question:** Do we want to use E=1000000 for all cases? Or do we want to use a different E for compressible and incompressible flow? Again related to #125 
* `flap_perp/SU2-CalculiX` is actually `flap_perp_2D/SU2-CalculiX`. E.g. on [this branch](https://github.com/precice/tutorials/tree/formatSU2-CCX-tutorial/FSI/flap_perp_2D/SU2-CalculiX) by @IshaanDesai.

**Comment by IshaanDesai** [comment]
Running the SU2 - FEniCS case with E = 4E+6 and inlet fluid velocity = 10.0 m/s leads to a highly unstable case. After some fine tuning the recommended values for a reasonable SU2 - FEniCS case are: E = 1E+6 and inlet fluid velocity = 1.0 m/s. These parameters also lead to a reasonable result for SU2 - CalculiX. Further tuning to bring the reasonable parameters and proposed parameters can be done to find the *optimal parameter set*.

**Comment by DavidSCN** [comment]
Yes, the cases are currently not consistent. As already commented by @BenjaminRodenberg , there was one inconsistency introduced by myself in he deal.II cases.

However, #146 will resolve the inconsistencies. As already described in the PR description, the new parameter configuration is based on [this paper (Fenics-Nutils)](https://arxiv.org/abs/2001.02654). The current capability of Nutils creates some restrictions on the fluid side and in order to justify the linearity of (some) structural solver, we need to consider some restrictions on the solid side. 

> Note: There is a nice table for conversion of these parameters on wikipedia at the bottom of the entry. I used the formulas given on wikipedia for computing the numbers marked with a *.

Agree, I like this table very much. The new parameter configuration (already described in the README in #146 ) looks the following way: mu (G)=1538461, lambda = 2307692 , rho = 3000 , E = 4e+6 , nu = 0.3.

> Running the SU2 - FEniCS case with E = 4E+6 and inlet fluid velocity = 10.0 m/s leads to a highly unstable case. After some fine tuning the recommended values for a reasonable SU2 - FEniCS case are: E = 1E+6 and inlet fluid velocity = 1.0 m/s. These parameters also lead to a reasonable result for SU2 - CalculiX. Further tuning to bring the reasonable parameters and proposed parameters can be done to find the optimal parameter set.

I have indeed not yet tried the Fenics case. In general, the setup you described first should be stable though (will check again with deal.II today). However, we cannot tune individual case-pairs in the new tutorials structure and in particular, we cannot change parameters on the structural side due to stability issues on the Fluid side (compressibility). I think I have not yet described the exact parameter setting in the README, but I changed the pressure gradient for SU2 so that we end up in a rather compressible region of Ma=0.3.

**Comment by IshaanDesai** [comment]
> However, we cannot tune individual case-pairs in the new tutorials structure and in particular, we cannot change parameters on the structural side due to stability issues on the Fluid side (compressibility).

I agree here. I would even suggest doing a joint parameter testing session on Zoom or Skype sometime. 

> but I changed the pressure gradient for SU2 so that we end up in a rather compressible region of Ma=0.3

This is interesting and I had overlooked this in my testing. Will test this and (hopefully) come back with some better results and more flexible parameters :+1:

**Comment by BenjaminRodenberg** [comment]
Since #146 is merged. Are all the cases consistent now? My status-quo for the parameters is the following:

![Screenshot from 2021-03-11 11-50-10](https://user-images.githubusercontent.com/5740604/110776160-078bb600-8260-11eb-8a91-a648da223676.png)

![Screenshot from 2021-03-11 12-07-36](https://user-images.githubusercontent.com/5740604/110778301-78cc6880-8262-11eb-830e-7997a0921d78.png)

Note: I took the following values as a basis for the Young's modulus

* FEniCS: https://github.com/precice/tutorials/blob/3ddf707ae306981aa1967bfb517eed235829f023/perpendicular-flap/solid-fenics/perp-flap.py#L30
* CCX: https://github.com/precice/tutorials/blob/3ddf707ae306981aa1967bfb517eed235829f023/perpendicular-flap/solid-calculix/flap.inp#L6
* deal.II: https://github.com/precice/tutorials/blob/3ddf707ae306981aa1967bfb517eed235829f023/perpendicular-flap/solid-dealii/linear_elasticity.prm#L26-L30

From my perspective #146 resolved all ambiguities and therefore, we can close this issue.

@DavidSCN can you do a final review whether my table/figure is consistent with the current status and then close this issue?

**Comment by DavidSCN** [comment]
> Since #146 is merged. Are all the cases consistent now? My status-quo for the parameters is the following:

Should be the case, yes. The given solid material specifications are now consistent and correspond to out setup, I checked it.  For the compressible fluid, the total temperature and the total pressure at the inlet are missing, but that's not a problem and not related to this/any issue. 

Thanks for all the tables!

**Comment by BenjaminRodenberg** [comment]
> The given solid material specifications are now consistent and correspond to out setup, I checked it. 

Thanks!

> For the compressible fluid, the total temperature and the total pressure at the inlet are missing...

What do you mean? The table gives `p_\infty = 101325 Pa` and `T_\infty = 288.15 K`. This is taken from

https://github.com/precice/tutorials/blob/3ddf707ae306981aa1967bfb517eed235829f023/perpendicular-flap/fluid-su2/euler_config_coupled.cfg#L54-L58

I also see

https://github.com/precice/tutorials/blob/3ddf707ae306981aa1967bfb517eed235829f023/perpendicular-flap/fluid-su2/euler_config_coupled.cfg#L92-L104

Do we also need this to properly define the case? If yes, please comment and I will update the table accordingly.

**Comment by DavidSCN** [comment]
I'm not 100% sure since I have not much experience with SU2, but I assume that the \infty values correspond to the far field values, i.e. the reference values. In order to define the boundary conditions you need to specify the inlet values and (for subsonic cases) a field at the outlet, e.g. the pressure.
