### ISSUE TITLE
Fix nutils-nutils heat transport case

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/tutorials#152]
#148 applies the new structure from #125 to the heat transport case. We also want to be able to run the heat transport case using nutils-nutils or any combination of fenics and nutils.

I will create a PR with a prototype implementation in a moment.

**Comment by BenjaminRodenberg** [comment]
I'll try to fix this issue until Apr. 21.

**Comment by MakisH** [comment]
@BenjaminRodenberg is this still open after having merged #153?

**Comment by BenjaminRodenberg** [comment]
Issue is solved, since #153 is merged.
