### ISSUE TITLE
Leftover directory FSI/

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#168]
We currently have this directory in `develop`: https://github.com/precice/tutorials/tree/develop/FSI

Is this a leftover? Can we delete it already?

**Comment by uekerman** [comment]
At least the `ridig_flap` will be removed as part of https://github.com/precice/tutorials/pull/145
I guess the `two_flap_perp_2D` is a forgotten leftover from https://github.com/precice/tutorials/pull/151 @DavidSCN ?

**Comment by DavidSCN** [comment]
IIRC the `two_flap_perp_2D` was not yet part of the `restructure` branch when I created #151. So, it is probably a left-over of the `restructure` -> `develop` merge. Anyway, can be deleted.
