### ISSUE TITLE
deal.II run.sh assumes ./elasticity

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#172]
Example: https://github.com/precice/tutorials/blob/develop/perpendicular-flap/solid-dealii/run.sh#L24

Similarly, the error message is not accurate:
```
"Unable to find the executable 'elasticity'. Either specify a prefix (-p=/path/to/elasticity) or make it discoverable at runtime (e.g. export PATH)"
```

Adding the deal.II adapter build dir in `PATH` does not work. We could find a nice way to make it work for both.

**Comment by DavidSCN** [comment]
I addressed it in #175. You can keep it open if you still like to work on this.
