### ISSUE TITLE
Use PEP8 formatting and implement CI

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/tutorials#177]
See https://github.com/precice/tutorials/pull/153#discussion_r607138785.

# Todo

- [x] implement CI similar to https://github.com/precice/python-bindings/blob/develop/.github/workflows/check-pep8.yml
- [x] format all python codes according to PEP8

**Comment by MakisH** [comment]
We should then also apply this for the elastictube1d (not yet in this repository).

**Comment by uekerman** [comment]
The CI would / should catch all python files, right? So, including future tutorials (like the elastictube1d).

**Comment by BenjaminRodenberg** [comment]
> The CI would / should catch all python files, right? So, including future tutorials (like the elastictube1d).

Exactly. https://github.com/precice/python-bindings/blob/develop/.github/workflows/check-pep8.yml checks all files in the repository (existing and future ones), but also excludes some (`--exclude ./spack/var/spack/repos/builtin/packages/py-pyprecice/package.py`). I'm not sure whether we can just "throw" autopep8 onto the whole repository and it figures out independently which files are relevant (python) and which are not (everything else). 

But I'm optimistic here: The python bindings repository is already consisting of different file types and autopep8 magically works. I don't expect severe problems with this repository.

**Comment by MakisH** [comment]
Closed by #185
