### ISSUE TITLE
turek-hron-fsi3/solid-fenics and turek-hron-fsi3/solid-dealii not consistent

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/tutorials#186]
https://github.com/precice/tutorials/blob/4ce3842580a38eaa400fec0e10ec31a014a37d22/turek-hron-fsi3/solid-fenics/precice-adapter-config-fsi-s.json#L1-L9

Still uses forces, not stresses like the corresponding deal.II case and the `precice-config.xml`:

https://github.com/precice/tutorials/blob/4ce3842580a38eaa400fec0e10ec31a014a37d22/turek-hron-fsi3/precice-config.xml#L22-L25

Related to #130.

**Comment by uekerman** [comment]
We decide to delete this case as our FEniCS solid model is only linear, so not suited for the FSI3

**Comment by BenjaminRodenberg** [comment]
I will clean this up in #187
