### ISSUE TITLE
elastic-tube-1d: Missing documentation elements for visualization

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/tutorials#188]
The documentation and code for visualization of the [PythonTube](https://github.com/precice/elastictube1d/tree/master/PythonTube) really need some polishing. Currently, it is really hard to understand how plots are created etc.

This is just a quick, unsorted collection of material:

* We can create VTK files with velocity and tube diameter. See [output.py](https://github.com/precice/tutorials/blob/master/elastic-tube-1d/fluid-python/output.py)
* ~~I do not know a nice way for using these VTK files in paraview.~~ The VTK files are used in plotting [here](https://github.com/precice/tutorials/blob/master/elastic-tube-1d/plot-vtk.py)
* ~~The script [fluid.py](https://github.com/precice/elastictube1d/blob/master/Postproc/fluid.py) allows us to create [this plot](https://raw.githubusercontent.com/wiki/precice/precice/images/elastictube_diameter.png). I do not think that this plot is really useful, but at least there exists some documentation on it [here](https://github.com/precice/precice/wiki/Running-the-1D-elastic-tube-example#postprocessing--visualization).~~ A newer plot is now available and provides much more relevant information regarding results.
* We have a nice [gif](https://raw.githubusercontent.com/wiki/precice/precice/images/tube.gif) of the elastictube. However, it is not documented, how this gif was actually created. With some insider knowledge, it is possible to find the code [here](https://github.com/precice/elastictube1d/blob/convergenceStudies/PythonTube/output.py#L172).

What would be nice: 

- [ ] ~~Merge the gif/video output from [`convergenceStudies`](https://github.com/precice/elastictube1d/tree/convergenceStudies) into `master`~~
- [x] Document: How do I create gif/video output? ([replace this paragraph](https://github.com/precice/precice/wiki/Running-the-1D-elastic-tube-example#postprocessing--visualization))
- [x] Find out how to make use of the VTK output or drop it.

**Comment by IshaanDesai** [comment]
Closed in https://github.com/precice/tutorials/pull/209
