### ISSUE TITLE
elastic-tube-1d: Python version needs considerably more iterations than C++ version

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/tutorials#191]
Observation by @fsimonis (https://github.com/precice/precice/pull/657#issuecomment-581396182):

```
1D-ElasticTube Python runs in serial, ~20x slower than C++ on my system.
```

~~This looks like there is an bug in the python tube (or at least something is not implemented in the optimal way).~~ The number of iterations needed by the python elastic tube is much higher than for the C++ version. We should try to find the reason for the difference in performance.

**Comment by BenjaminRodenberg** [comment]
I corrected my statement from above: It's not a bug in the python tube, but actually cpp and python are doing different things. According to @carme-hp it seems like the python tube is actually behaving correctly and therefore also used as reference.

**Comment by MakisH** [comment]
With #197, the two variants now have very similar total number of iterations:
- C++: 791
- Python: 857
