### ISSUE TITLE
elastic-tube-1d: Make matplotlib and vtk an optional dependency

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/tutorials#192]
The python tube requires `matplotlib` and `vtk` for plotting and output. Currently, these dependencies are **mandatory** due to the following line in `FluidSolver.py`:

https://github.com/precice/elastictube1d/blob/02d9e8f50c32343dcf6a38541323120a0230c453/python/FluidSolver.py#L8

Even users that do not want to do plotting or write output have to install `matplotlib` and `vtk`. We should try to make these dependencies optional.

**Comment by IshaanDesai** [comment]
Discussion with team led to the conclusion that having matplotlib and vtk as dependencies is not a problem. Related issue: #190
