### ISSUE TITLE
elastic-tube-1d: Merge serial and parallel cpp solvers

### ISSUE THREAD

**Issue by uekerman** [precice/tutorials#193]
We currently basically duplicate the cpp fluid and structure solvers to have a serial and a parallel case. 
This is confusing and hard to maintain. I also don't see a good reason for this. I suggest to merge the serial and the parallel solvers.

**Comment by fsimonis** [comment]
We removed the parallel case of the fluid solver in #197

**Comment by MakisH** [comment]
Closed by #197.
