### ISSUE TITLE
elastic-tube-1d: Parallel run in the cpp version

### ISSUE THREAD

**Issue by carme-hp** [precice/tutorials#194]
First, note that there is an open issue regarding the [cpp results](https://github.com/precice/elastictube1d/issues/41#issue-855396140). Second, note that ´FluidSolver´ calls different functions in case of a serial or a parallel run. This is of course not desirable and both functions should be unified when the mentioned issue is fixed.

For now, the function `fluidComputeSolutionParallel` is solving a different scenario than `fluidComputeSolutionSerial`. The scenario that `fluidComputeSolutionParallel` is solving is the first one that was historically developed for elastic tube and is different than the one that was implemented in python later on. I modified `fluidComputeSolutionSerial` a posteriori to mimic the scenario solved in the python version and this is the reason why we have to different scenarios in the cpp.

In any case, this is what the results when using `fluidComputeSolutionSerial`version looked like originally:

![diameter](https://user-images.githubusercontent.com/71499004/114310822-7de43800-9aec-11eb-9a83-462a85f36b09.png)

Due to the modifications done in `FluidSolver.cpp` the parallel version is not providing any meaningful results at the moment.

**Comment by fsimonis** [comment]
We decided to remove the parallel version of the elasitic-tube-1d fluid-cpp solver as it does not showcase any real use-case.

**Comment by MakisH** [comment]
Closed by #197
