### ISSUE TITLE
Socket Communication error

### ISSUE THREAD

**Issue by smartmenia1** [precice/tutorials#2]
Hello,

i have installed SU2 and Calculix as well as Precice with the corresponding modules. The testcases for precice run all of them as well as SU2 CFD simulation testcases and Calculix solver. 

Running the FSI Tutorial results to a **socket communication error**. 
[Calculix.txt](https://github.com/precice/tutorials/files/1771651/Calculix.txt)

Can anyone give me idea why it's not working? 

Best regards

**Comment by MakisH** [comment]
Hello @smartmenia1,

1. What is the respective output of SU2?

2. Which version or commit of preCICE and the adapters are you using? (in the log file I see that you use CalculiX 2.13).

Best regards,
Makis

**Comment by smartmenia1** [comment]
Hello,

i use the following adapters: 
- SU2 adapter from Version 5.00  after the commit  on 30 Jan. 
[SU2.txt](https://github.com/precice/tutorials/files/1771772/SU2.txt)

- CalculiX adapter after the commit  on 30 Jan. 
- Precice  Version v1.0.2

following the steps from https://github.com/precice/precice/wiki/FSI-tutorial. 

Best regards

**Comment by MakisH** [comment]
It looks like there is a problem with the SU2 simulation. The "socket communication" error is misleading here, as it is thrown just because the SU2 participant disappears while the CalculiX participant is still in the `advance()`.

Tail of the SU2 log file:
```
------------------------------ Begin Solver -----------------------------
 Deforming the volume grid due to preCICE simulation.
Computing volumes of the grid elements.
Min. volume: 0.00113526, max. volume: 0.111064.
CSysMatrix::MatrixVectorProduct(const CSysVector&, CSysVector): nVar values incompatible.
terminate called after throwing an instance of 'int'
Run finished at Thu Mar  1 16:28:10 2018
```
According to the error message, the problem seems to be in the `CSysMatrix::MatrixVectorProduct(const CSysVector&, CSysVector)`. I am not familiar with the SU2 adapter, however other developers, such as @arusch, will probably be able to help you.

**Comment by arusch** [comment]
Hi,

can you confirm that the SU2 adapter is, indeed, the one intended for v5.0.0 „Raven“ of SU2? (E.g. check the version number in the adapter README.md, in the su2InstallationScript or in any of the files in the directory „replacement_files“.)

If you have the correct version, let me know and I will try to reproduce the error and keep you updated on that issue.

**Comment by uekerman** [comment]
I added a [small entry in the wiki](https://github.com/precice/precice/wiki/Error-Messages) explaining the `ERROR: Receive failed: read: End of file`.

**Comment by smartmenia1** [comment]
Hi arusch,

that's the version 5.0.0 "Raven" that's correct. I have check this in "README.md" and one of the files in the folder replacement.

Best regards

**Comment by smartmenia1** [comment]
Hi,

i have fixed that issue. I have reinstalled first the adapter and then SU2. 
It works. :) 

Thanks a lot to all of you for your fast answers and help , don't waste your time anymore on that issue. I think it was the order of installation. Everything works perfect. Nice job.

Best regards

**Comment by arusch** [comment]
Very nice. Thanks for your feedback!
