### ISSUE TITLE
Nutils code in prependicular-flap/fluid-nutils does not work for Nutils v7.0

### ISSUE THREAD

**Issue by IshaanDesai** [precice/tutorials#217]
- Tutorials state (last commit / release): https://github.com/precice/tutorials/tree/d2c70c09e6ae50c2a586edfe9008730902ebb980
- Versions of solvers and adapters used: Nutils `v7.0a0` 
- preCICE version: v2.2.1

The Nutils code in `perpendicular-flap/fluid-nutils` does not work and produces the following error:
```
Traceback (most recent call last):
  File "fluid.py", line 13, in <module>
    @function.replace
AttributeError: module 'nutils.function' has no attribute 'replace'
```
Nutils was installed by cloning the repository from GitHub and running `python3 -m pip install --user .`

**Comment by uekerman** [comment]
The tutorial only works with the latest Nutils release, v6. For Nutils develop (v7), the tutorial needs some updating.

**Comment by IshaanDesai** [comment]
[Nutils v7.0](https://github.com/evalf/nutils/releases/tag/v7.0) has been released and hence this issue is now relevant

**Comment by uekerman** [comment]
Some comment @gertjanvanzwieten wrote to me a while back

> Actually, in master we extended to solver methods to accept multiple targets & residuals, which means we don't have to chain anymore, which also means dofs don't need to be vectors anymore; instead we can define `u_i = basis_n ?udofs_ni`, which simplifies things considerably. As soon as we release v7, I propose to rework this example to the new form so it becomes insensitive to things like dof ordering that really shouldn't reach the surface at any point.

**Comment by uekerman** [comment]
Let's document which tutorials version requires which Nutils version on https://precice.org/adapter-nutils.html

**Comment by gertjanvanzwieten** [comment]
I'd be happy to help port things over to Nutils 7 if that's welcome.

**Comment by uekerman** [comment]
Any help would be much appreciated :hugs: 

Relevant codes are:
- partitioned heat conduction: [heat.py](https://github.com/precice/tutorials/blob/develop/partitioned-heat-conduction/nutils/heat.py)
- flow over heated plate: [solid.py](https://github.com/precice/tutorials/blob/develop/flow-over-heated-plate/solid-nutils/solid.py)
- perpendicular flap: [fluid.py](https://github.com/precice/tutorials/blob/develop/perpendicular-flap/fluid-nutils/fluid.py)

**Comment by gertjanvanzwieten** [comment]
Cool, I'll try to look into it this week still

**Comment by MakisH** [comment]
I added an overview of the current support state in https://github.com/precice/precice.github.io/pull/228. The main script we still need to port is https://github.com/precice/tutorials/blob/develop/perpendicular-flap/fluid-nutils/fluid.py

(thanks for all the help already in the other scripts! :hugs:)

**Comment by MakisH** [comment]
I think that we can close this, now that we install Nutils separately for each tutorial.
