### ISSUE TITLE
solid-fenics/Solid/ folder not removed when cleaning scripts are run

### ISSUE THREAD

**Issue by IshaanDesai** [precice/tutorials#221]
- Tutorials state (last commit / release): https://github.com/precice/tutorials/commit/d2c70c09e6ae50c2a586edfe9008730902ebb980

When FEniCS is run with any case, a folder `solid-fenics/Solid/` is generated and results are stored in it. When the case is cleaned using the given cleaning script the folder `solid-fenics/Solid/` is not removed and needs to be manually deleted.

**Comment by MakisH** [comment]
I guess this only means that the related `clean_fenics()` function is not up-to-date: https://github.com/precice/tutorials/blob/master/tools/cleaning-tools.sh#L71-L81

It currently removes `FSI-S/*` folders, just update this line.

**Comment by IshaanDesai** [comment]
Resolved in https://github.com/precice/tutorials/commit/5470dd0d99bd63d5b7d8564bcfc471c7e978c822
