### ISSUE TITLE
elastic-tube-1d: Unnecessary readBlockScalarData

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/tutorials#231]
The following `readBlockScalarData` statements looks wrong and is inconsistent with the python version of the 1d tube:

https://github.com/precice/tutorials/blob/6d90ae3eb179113beb400e472c8832e29a48db9b/elastic-tube-1d/fluid-cpp/src/FluidSolver.cpp#L104-L106

Compared to the original code (see https://github.com/precice/elastictube1d/blob/master/fluid-cpp/FluidSolver.cpp) this statement has been added. Is there a specific reason?

I did some experiments related to this change and will document them here, since this might be helpful for https://github.com/precice/precice/pull/1036:

| commit | comment | `fluid-cpp` + `solid-cpp` remove statement above (fa75a39) | `fluid-cpp` + `solid-cpp` keep statement above (46ce8abee8dea365005da40f6e016a12f4bd97fd) | `fluid-python` + `solid-python` (46ce8abee8dea365005da40f6e016a12f4bd97fd) |
|----------------------------------------------------------------------------------------------------------------------|---|---|---|---|
https://github.com/precice/precice/commit/3ff0899092862ad6f081df033ca9b51d0041befa | pre https://github.com/precice/precice/pull/1004| :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark:  |
https://github.com/precice/precice/commit/54707b3902af7d79b28ac276f304c31c6fcf5433 |  current state https://github.com/precice/precice/pull/1036 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
https://github.com/precice/precice/commit/40eca9dea4802f8dc59426eeefc39d95269042a4 |  current state `precice:develop` | :x: | :x:  | :x: |
https://github.com/precice/precice/commit/c9c90b23abbe0ec9380266d68c51c75374ab6a81 | merge `precice:develop` into https://github.com/precice/precice/pull/1036 | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark:  |

:heavy_check_mark: -> elastic-tube-1d works as expected
:x: -> elastic-tube-1d breaks as described in https://github.com/precice/precice/issues/1032

**Comment by MakisH** [comment]
I got very confused on what you meant by "looks wrong". I guess you want to point out that it is duplicate, as it appears again later inside the same loop.

I am not sure what the experiments are showing (what does :x: mean?), but it anyway indeed looks duplicate and thus wrong.

**Comment by BenjaminRodenberg** [comment]
> I am not sure what the experiments are showing (what does x mean?), but it anyway indeed looks duplicate and thus wrong.

I added a statement below the table.

**Comment by fsimonis** [comment]
Can you enlighten me why this looks wrong?

This is textbook API usage.
* initialize
* initializeData (ok, should maybe be wrapped in an action check)
* read if available (not really required) 
* coupling ongoing?
* read if available
* verwursteln
* write if required

These readdata statements have to return the same information, so I am a bit puzzled about why this should be wrong.

**Comment by fsimonis** [comment]
Why does this read statement look wrong?

This looks like textbook API usage
* initialize
* initializeData
* read if available (ok, this is not required)
* while coupling ongoing
* create checkpoint if required
* read if available
* solve
* write if required
* advance
* restore checkpoint if required

The read data call that looks weird to me is 
https://github.com/precice/tutorials/blob/6d90ae3eb179113beb400e472c8832e29a48db9b/elastic-tube-1d/fluid-cpp/src/FluidSolver.cpp#L127-L130

**Comment by uekerman** [comment]
There are definitely too many reads in there, but it is not forbidden to call read multiple times. This should never influence the results.

```
initialize
while(ongoing){
  read
  solve
  write
  advance
}
```

```
initialize
read
while(ongoing){
  solve
  write
  advance
  read
}
```
are both correct and allowed.

**Comment by BenjaminRodenberg** [comment]
Quick summary:

* There are too many reads (maybe "incorrect" was a bit too strong in the header of this Issue)
* There are two possibilities (https://github.com/precice/tutorials/issues/231#issuecomment-889806830), current implementation is a mixture of both.

What do you think about the solution I implemented in https://github.com/precice/tutorials/pull/232? Feel free to leave a review. I change the title of this issue for more clearity.

**Comment by fsimonis** [comment]
So, this means that we have a bug in precice. The elastictube1d is just a bit overly verbose.

So we should implement tests that read and write multiple times.

**Comment by BenjaminRodenberg** [comment]
> So, this means that we have a bug in precice. The elastictube1d is just a bit overly verbose.

Yes. But this bug is already documented in https://github.com/precice/precice/issues/1032, a fix is on the way (https://github.com/precice/precice/pull/1036) and a test, as well (https://github.com/precice/precice/pull/1050). Or do you mean a different bug?

> So we should implement tests that read and write multiple times.

Opened an issue on this: https://github.com/precice/precice/issues/1055

**Comment by MakisH** [comment]
Closed by https://github.com/precice/tutorials/pull/232
