### ISSUE TITLE
partitioned-elastic-beam: Visualization script is still in Python 2

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#235]
File: https://github.com/precice/tutorials/blob/6d90ae3eb179113beb400e472c8832e29a48db9b/partitioned-elastic-beam/visualize.py

With a quick look, the `print` needs parentheses. After fixing this, Python complains about `xrange`. Maybe there are a few more.

**Comment by mohamad-altaweel** [comment]
we can close the issue right now

**Comment by DavidSCN** [comment]
Thanks @mohamad-altaweel
