### ISSUE TITLE
CHT flow-over-plate with OpenFOAM and FEniCS/Nutils: compute heat flux from temperature

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/tutorials#25]
The heat flux computation of both approaches (OpenFOAM/FEniCS and OpenFOAM/Nutils) is currently different. Are both versions correct or is one of them wrong? In the end one consistent way form computing the flux would be desirable.

**Comment by BenjaminRueth** [comment]
A few more, possibly not directly related comments:

* We should also add tests to make sure that the flux computation is correct.
* See also https://github.com/precice/fenics-adapter/issues/3

**Comment by BenjaminRueth** [comment]
I tried out using `grad(u)` to compute the flux (see https://github.com/precice/tutorials/commit/54800087b3a2877c9a7eba5996cfc6f72e6826ae). Some comments on this:

* the approach follows the [FEniCS tutorial book, section 5.5.2](https://fenicsproject.org/pub/tutorial/pdf/fenics-tutorial-vol1.pdf)
* using this approach increases the error. Why?
* depending on the meshing, we get different results. By default FEniCS uses the `right` option for meshing. Using other options changes the flux at the upper and lower boundary. For additional options see [here](https://fenicsproject.org/docs/dolfin/1.4.0/python/demo/documented/built-in_meshes/python/documentation.html).

**Comment by uekerman** [comment]
In both tutorials, we use the weak form for the flux computation. This is consistent and the right way to go. Using `grad()` violates the Galerkin projection and is known to increase the error. I will document this properly (at some point :wink:).
