### ISSUE TITLE
Displacement results of elastic-tube-3d for FEniCS and CalculiX differ significantly

### ISSUE THREAD

**Issue by IshaanDesai** [precice/tutorials#259]
In https://github.com/precice/tutorials/pull/222 FEniCS was added as a solid participant to the elastic-tube-3d tutorial case. A watch point was also added on the solid tube to check the displacement in the center of the tube. The results for CalculiX and FEniCS coupled with OpenFOAM are as follows:
![tutorials-elastic-tube-3d-plot](https://user-images.githubusercontent.com/44898158/152822205-a61220ca-bd87-4fa7-ac72-8f313de57567.png)
It is evident that the results radial displacement differ greatly on whether CalculiX or FEniCS is used. I think this is the case because of the choice of the elements and also the solvers in CalculiX and FEniCS. The CalculiX participant has [C3D10](https://web.mit.edu/calculix_v2.7/CalculiX/ccx_2.7/doc/ccx/node33.html) elements. For the FEniCS participant we use the [Cylinder](https://bitbucket.org/fenics-project/mshr/wiki/API/Cylinder) function to construct the geometry. The FEniCS version we use offers very little control over the type of elements we can have, especially when we use in-built geometry constructing functions. In FEniCS-X there is greater control over the choice of elements.

This needs to be investigated further and eventually resolved.

**Comment by maxfirmbach** [comment]
I was having a look at that example as I want to also make a dune-solid participant for a 3d case.

@IshaanDesai could it be that the parameters for density and young's modulus are different in the fenics and calculix case?
Fenics: in solid.py, rho = 3000, E = 4000000, nu = 0.3
Calculix: in tube.inp, rho = 1200, E = 300000, 0.3

That would be a reason for the big difference in the plot above.
Please correct my if I'm wrong though!

**Comment by maxfirmbach** [comment]
I have an working implementation with the DUNE-Adapter (using rbf mapping) and first order elements and obtain the following results:

![tutorials-elastic-tube-3d-displacement-all-watchpoints](https://user-images.githubusercontent.com/76822743/153913819-b57e9b18-8474-4f13-9f23-1ce24e05fc08.png)

So I guess by changing the material parameters inside Fenics the result should look similar.

**Comment by IshaanDesai** [comment]
Thank you @maxfirmbach for pointing this out! I must accept I did not spend a lot of time tuning the material properties for the FEniCS participant. I will test it with the changes and update my results here.

**Comment by IshaanDesai** [comment]
I ran the cases again with FEniCS and CalculiX having the same material properties and the results indeed look to be in agreement:
![tutorials-elastic-tube-3d-displacement-all-watchpoints](https://user-images.githubusercontent.com/44898158/158804655-8c3d5140-6e39-4ae4-947e-a4f4bfdd3558.png)

**Comment by IshaanDesai** [comment]
Resolved in https://github.com/precice/tutorials/commit/9e4144e4bfa8e42e779a01e4ae1cd9189aff4b25
