### ISSUE TITLE
FASTEST adapter problems

### ISSUE THREAD

**Issue by jessicamms** [precice/tutorials#26]
Hi, I try to modify the adapter for FASTEST because our current adapter does not work with the extrapolation and the parallel coupling does not present advantages to the serial coupling. The setup of the meshes and initial configuration works well, but our coupling process is different from the adapter example, and I think that maybe it is the reason for my problems. 

the original implementation is the following:

while (not simulationDone()){ // time loop
	dt = beginTimeStep(); // e.g. compute adaptive dt 
	dt = min(precice_dt, dt);
        
        while (iterout<=fsiiterout) // fsi coupling

		computeTimeStep(dt); // the fluid calculations
		computeForces(forces);
		
		precice.writeBlockVectorData(forceID, vertexSize, vertexIDs, forces);

       		precice.readBlockVectorData(displID, vertexSize, vertexIDs, displacements);
		setDisplacements(displacements);

		if(precice.isActionRequired(cowic)){
			precice.fulfilledAction(cowic);
	        }

	        precice_dt = precice.advance(dt);
 
		precice.readBlockVectorData(displID, vertexSize, vertexIDs, displacements);
		setDisplacements(displacements);
 
		if(precice.isActionRequired(cowic)){
			precice.fulfilledAction(cowic);
	        }
		if(precice.isActionRequired(coric)){ // timestep not converged
			precice.fulfilledAction(coric);
		}
		else{ // timestep converged
			endTimeStep(); // e.g. update variables, increment time
                     iterout = ifsiiterout  // out the fsi cycle
		}
	 }
}

The principal differences are the order of the calling to the process, and in FASTEST we have an extra cycle to make the fsi coupling (because this was the way to work with mppci).

Do you think that it is necessary to modify in order to use the parallel coupling and the extrapolation?

I modified the adapter as the wiki example and I eliminated the 'while for the fsi coupling'. But now the time step increase with every fsi iteration. then my questions are:
Is it necessary to do the 'while fsi coupling' ?
Is it important to read the displacement before to calculate the fluid?

**Comment by uekerman** [comment]
Hi @jessicamms! 

In general, it's probably a good idea to change a few things in the FASTEST adapter. preCICE simply has a different level of API than MpCCI (a more high-level one), so following the MpCCI syntax for the preCICE adapter is not advisable. "read" and "write" is not the same as "receive" and "send". 

It's hard to tell what exactly the current problem is, but I collect some general remarks that might help you:
* Parallel and serial coupling should not require any changes in the adapter. This is actually the whole idea of the high-level API of preCICE
* `while (iterout<=fsiiterout)` should not be necessary. You should leave the coupling loop to preCICE. A simple `while(isCouplingOngoing)` should be enough to detect the end of the simulation
* Is "write-checkpoint" and "read-checkpoint" really empty in your case? How do you do your implicit coupling then?
* It's good advice to put your "read" and "write" statements within a `isReadDataAvailable` and `isWriteDataRequired` clause, respectively.  


> I modified the adapter as the wiki example and I eliminated the 'while for the fsi coupling'. But now the time step increase with every fsi iteration. 

You should only increase the timestep counter in FASTEST in the "else clause" of read-iteration-checkpoint. Alternatively, there is also a `isTimestepComplete`.  

> Is it important to read the displacement before to calculate the fluid?

In general, yes. You should have new data before you solve your step. Also, don't forget that you might already receive new data in `initialize`.

We currently use the issue tracking system of GitHub for bugs, features, ... code dev only. The perfect place for such a usage question would be the [mailing list](https://mailman.informatik.uni-stuttgart.de/mailman/listinfo/precice). For quick questions, [gitter](https://gitter.im/precice/Lobby).
