### ISSUE TITLE
heat-exchanger crashing at time=5

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#260]
- Tutorials state (last commit / release): b99dfb (essentially v202104.1.1 + documentation updates)
- Versions of solvers and adapters used:
    - OpenFOAM v2106 (tried also v2012 and v2112)
    - OpenFOAM adapter v1.0.0 (tried also develop)
    - CalculiX 2.16 (tried also 2.19)
    - CalculiX adapter from master (1b1849), essentially the distribution
- preCICE version: v2.3.0 (same for v2.2.1, same for develop)

OpenFOAM is crashing at `Time=5` with a negative temperature:

- [fluid-inner-openfoam.log](https://github.com/precice/tutorials/files/8018528/fluid-inner-openfoam.log)
- [solid-calculix.log](https://github.com/precice/tutorials/files/8018531/solid-calculix.log)
- [fluid-outer-openfoam.log](https://github.com/precice/tutorials/files/8018532/fluid-outer-openfoam.log)

In the distribution VM [v202104.1.0](https://app.vagrantup.com/precice/boxes/precice-vm/versions/202104.1.0), the simulation passes this point (at least to `Time=18`, did not check for later).

The only difference I see is Ubuntu 21.10 instead of 20.04.

Can anyone reproduce this?

**Comment by IshaanDesai** [comment]
I tried to reproduce this issue and did not see the failure. The states of repositories that I ran the case with:

* tutorials https://github.com/precice/tutorials/commit/b99dfba0a5fe6c9947e90da3242e5e228fbc6759
* OpenFOAM adapter: https://github.com/precice/openfoam-adapter/commit/cf4eb0f389708a35bea2fd9b762b245a9dc37114 and v2012
* CalculiX adapter https://github.com/precice/calculix-adapter/commit/1b18495d4bfda2580e4b045cd2b75f9fcdadd704 and v2.16

**Comment by KyleDavisSA** [comment]
I do not get a failure for the heat exchanger:

- Tutorials: https://github.com/precice/tutorials/commit/b99dfba0a5fe6c9947e90da3242e5e228fbc6759
- OpenFOAM v2012
- OpenFOAM adapter: v1.0.0: https://github.com/precice/openfoam-adapter/commit/22568dc8c26cedf6f795bcf69927c63b307bd4c6
- Calculix v2.16
- Calculix Adapter: https://github.com/precice/calculix-adapter/commit/1b18495d4bfda2580e4b045cd2b75f9fcdadd704

**Comment by IshaanDesai** [comment]
I tried to reproduce this issue and **did not see the failure** yet again. The states of repositories that I ran the case with:

* tutorials https://github.com/precice/tutorials/commit/b99dfba0a5fe6c9947e90da3242e5e228fbc6759
* OpenFOAM adapter: https://github.com/precice/openfoam-adapter/commit/cf4eb0f389708a35bea2fd9b762b245a9dc37114 and v2012
* CalculiX adapter https://github.com/precice/calculix-adapter/commit/eae5fc60730ce083fecf182c70503d969c8c7971 and v2.19

**Comment by MakisH** [comment]
Then let's close this and I will reopen if I manage to reproduce it.

**Comment by MakisH** [comment]
I can confirm that the simulation completes and the results look reasonable in the VM (Ubuntu 20.04).

**Comment by MakisH** [comment]
Has anybody actually tried reproducing this on anything else than Ubuntu 20.04? I find it strange that I still get it on my 21.10 system and I don't know if it is specific to me, or specific to the dependencies I am using.

**Comment by boris-martin** [comment]
@MakisH I just reproduced the crash on Ubuntu 22.04, CalculiX 2.19 (master branch of the adapter), OpenFOAM 2112 from Ubuntu package and master branch of preCICE. I'll try to investigate.

**Comment by boris-martin** [comment]
I tried with older versions of the adapter (up to Nov 2020) and none of them works. I imagine the problem is either OS-dependant or OpenFOAM-related.

**Comment by MakisH** [comment]
> Digging in the dark: Does it help if you decrease the `time-window-size` to "0.5"?

This is actually a steady-state case, so a `time-window-size` of `0.5` would be a bit strange here (still seems to run, though, and it crashes at T=2.5, i.e., at the 5th step).

But, as I was trying to rerun the case, I noticed that one can trigger the same error by running the fluid-inner-openfoam case without preCICE (disabling the adapter in `system/controlDict`). This indeed makes it related to OpenFOAM, or the case setup.
