### ISSUE TITLE
FSI with OpenFoam and CalculiX: specify Fluid Solver

### ISSUE THREAD

**Issue by richahert** [precice/tutorials#29]
The readme and runFluid script have no Comment on the Fluid Solver that the user should change for older OpenFOAM versions (that are stated as compatible in the readme). I think that should be mentioned somewhere in the readme. 

Otherwise the runFluid script results in the following error that does not lead new users to the fix:

```
--> FOAM FATAL ERROR: 
Error in the preCICE adapter: 
There was a problem while configuring the adapter. See the log for details.e pointVectorField are
0()

    From function void adapterInfo(std::__cxx11::string, std::__cxx11::string)
    in file Utilities.C at line 31.

FOAM exiting

Looking for any time directories without results (e.g. stray functionObjectProperties files, see issue #26 on GitHub)...
```
The solution of changing the solver name is described in the Allrun sript though:
```
        echo "  ### WARNING ### Make sure to use the correct solver for your OpenFOAM version! (pimpleFoam for OpenFOAM v1806, OpenFOAM 6, or newer, vs pimpleDyMFoam for older) You may change this in your Fluid/system/controlDict file, if needed."
```

**Comment by MakisH** [comment]
Thanks, @richahert! I will look into this.
