### ISSUE TITLE
CHT ccx_preCICE never starts computing

### ISSUE THREAD

**Issue by kunstrasenspringer** [precice/tutorials#3]
Hi,
I'm trying to work through the [CHT-tutorial](https://github.com/precice/precice/wiki/Tutorial-for-CHT-with-OpenFOAM-and-CalculiX). I'm using docker to realize the tutorial. You can find the Dockerfile (Dockerfile.of-ccx) [here](https://github.com/kunstrasenspringer/precice_st/tree/develop). Openfoam starts and finishes to compute (I set the endTime to 20.0), but ccx_preCICE starts and never ends. If I tail Solid.log, I get following output:

_Read data 'Sink-Temperature-Inner-Fluid' found.
Read data 'Heat-Transfer-Coefficient-Inner-Fluid' found.
Write data 'Sink-Temperature-Solid' found.
Write data 'Heat-Transfer-Coefficient-Solid' found.
Read data 'Sink-Temperature-Outer-Fluid' found.
Read data 'Heat-Transfer-Coefficient-Outer-Fluid' found.
Write data 'Sink-Temperature-Solid' found.
Write data 'Heat-Transfer-Coefficient-Solid' found.
(0) 17:58:30 [impl::SolverInterfaceImpl]:213 in initialize: Setting up master communication to coupling partner/s_

This happens in 'sequentiell' (./Allrun) and in 'parallel' (./Allrun_parllel). Also tried to start the simulation with 3 seperate terminals and manually typed commands, same outcome. 

The setup:
OS: ubuntu 18.04
preCICE: 1.0.3
ccx: 2.12
ccx-adapter: 2.12
openfoam: 5.x-197d9d3bf20a
openfoam-adapter: commit 36852e081022b3d58c489643e8ac48a3b92a0fea

Can somebody help me?
Best regards.

**Comment by MakisH** [comment]
Hi @kunstrasenspringer,

this looks like the OpenFOAM function object is not loaded, which usually means that there is some linking problem. Check the `ldd.log` that must have been produced when you built the adapter to see what is going wrong.

Best regards,
Makis

**Comment by kunstrasenspringer** [comment]
Hi Makis,

Thank you for the quick reponse!
You are right. I checked `ldd.log` and says: `ldd: /libpreciceAdapterFunctionObject.so: No such file or directory`. What do I have to do next?

Best regards,
kunstrasenspringer

**Comment by MakisH** [comment]
This looks like your `${FOAM_USER_LIBBIN}` is not defined when you compile the adapter. This should be already defined if you have loaded the OpenFOAM environment. But then it wouldn't even compile, does it? Is there anything suspicious in the `wmake.log`?

Do you load the `$FOAM_ETC/bashrc` file after installing OpenFOAM? You can find this in the OpenFOAM installation instructions.

**Comment by kunstrasenspringer** [comment]
I did load `$FOAM_ETC/bashrc` in the Dockerfile, but `${FOAM_USER_LIBBIN}` wasn't set. It never compiled and did not complained, so I thought everything went right. Now i load it in combination with `./Allwmake` and it is set, but now i have an other error dependent on yaml:

_wmakeLnInclude: linking include files to ./lnInclude
Making dependency list for source file preciceAdapterFunctionObject.C
could not open file yaml-cpp/yaml.h for source file preciceAdapterFunctionObject.C due to No such file or directory
Making dependency list for source file Adapter.C
could not open file yaml-cpp/yaml.h for source file Adapter.C due to No such file or directory
Making dependency list for source file CHT.C
could not open file yaml-cpp/yaml.h for source file CHT/CHT.C due to No such file or directory
Making dependency list for source file SinkTemperature.C
Making dependency list for source file HeatTransferCoefficient.C
...
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam-dev/src/finiteVolume/lnInclude -I/opt/openfoam-dev/src/meshTools/lnInclude -I/opt/openfoam-dev/src/transportModels/ -I/opt/openfoam-dev/src/transportModels/compressible/lnInclude -I/opt/openfoam-dev/src/thermophysicalModels/basic/lnInclude -I/opt/openfoam-dev/src/TurbulenceModels/turbulenceModels/lnInclude -I/opt/openfoam-dev/src/TurbulenceModels/compressible/lnInclude -I/opt/openfoam-dev/src/TurbulenceModels/incompressible/lnInclude  -I/home/alice/precice/src/precice -I../ -DADAPTER_DEBUG_MODE -IlnInclude -I. -I/opt/openfoam-dev/src/OpenFOAM/lnInclude -I/opt/openfoam-dev/src/OSspecific/POSIX/lnInclude   -fPIC -c Adapter.C -o Make/linux64GccDPInt32Opt/Adapter.o
Adapter.C: In member function 'void preciceAdapter::Adapter::adjustSolverTimeStep()':
Adapter.C:641:65: error: no matching function for call to 'Foam::Time::setDeltaT(double&, bool)'
     const_cast<Time&>(runTime_).setDeltaT(timestepSolver_, false);
                                                                 ^
In file included from /opt/openfoam-dev/src/finiteVolume/lnInclude/fvCFD.H:6:0,
                 from Interface.H:6,
                 from Adapter.H:4,
                 from Adapter.C:1:
/opt/openfoam-dev/src/OpenFOAM/lnInclude/Time.H:516:26: note: candidate: virtual void Foam::Time::setDeltaT(const dimensionedScalar&)
             virtual void setDeltaT(const dimensionedScalar&);
                          ^
/opt/openfoam-dev/src/OpenFOAM/lnInclude/Time.H:516:26: note:   candidate expects 1 argument, 2 provided
/opt/openfoam-dev/src/OpenFOAM/lnInclude/Time.H:519:26: note: candidate: virtual void Foam::Time::setDeltaT(Foam::scalar)
             virtual void setDeltaT(const scalar);
                          ^
/opt/openfoam-dev/src/OpenFOAM/lnInclude/Time.H:519:26: note:   candidate expects 1 argument, 2 provided
/opt/openfoam-dev/wmake/rules/General/transform:25: recipe for target 'Make/linux64GccDPInt32Opt/Adapter.o' failed
make: *** [Make/linux64GccDPInt32Opt/Adapter.o] Error 1_ 

but yaml is installed

**Comment by MakisH** [comment]
I think that we should continue the discussion on [Gitter](https://gitter.im/precice/Lobby), as this is actually multiple problems combined and not an issue with the tutorial. Closing this for now, please contact me (even privately if you prefer) there and send me your Dockerfile. :-)
