### ISSUE TITLE
Compatibility of Nutils cases with preCICE v3

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#312]
See the [preCICE v3 migration guide](https://precice.org/couple-your-code-porting-v2-3.html).

Related issues/PRs in other adapters:
- OpenFOAM: https://github.com/precice/openfoam-adapter/issues/235
- FEniCS: https://github.com/precice/fenics-adapter/pull/153

Also: Enable subcycling for partitioned-heat-conduction, follow-up of https://github.com/precice/tutorials/pull/281

**Comment by BenjaminRodenberg** [comment]
Duplicate? #369
