### ISSUE TITLE
FSI with CalculiX requires CGX (can we get rid of it?)

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#35]
For the FSI tutorials with OpenFOAM and CalculiX (and potentially other), we require that the user already has CGX installed. This is not very difficult (it is, I find, easier than CalculiX, there are even [prebuilt binaries](http://www.dhondt.de/cgx_2.15.bz2)), but it still is one additional piece of software.

Can we already provide the case prepared, so that the user does not have to install CGX as well?

**Comment by shkodm** [comment]
I did for the systemtests, so I can add it here as well.

**Comment by MakisH** [comment]
Thanks! Please also update the tutorials' wiki pages then. or don't merge until we update them.

**Comment by munkapas** [comment]
Please provide the tutorials with pre-built CalculiX models for the cylinderFlap FSI tutorial, so that we do not need to install CGX to run the tutorials. Figuring out how to install CGX seems just impossible...

**Comment by MakisH** [comment]
As somebody asked earlier today, here are the additional files that CGX produces for the flap_perp and cylinderFlap tutorials (CGX 2.13):
[cylinderFlap-Solid.tar.gz](https://github.com/precice/tutorials/files/4443754/cylinderFlap-Solid.tar.gz)
[flap_perp-Solid.tar.gz](https://github.com/precice/tutorials/files/4443755/flap_perp-Solid.tar.gz)

We could probably just ship these files with the tutorial.

**Comment by munkapas** [comment]
Thank you so much for providing the solid model files!

**Comment by MakisH** [comment]
This is now fixed in `develop`.
