### ISSUE TITLE
Add some machine readable file describing the versions going together to make up a reference output

### ISSUE THREAD

**Issue by valentin-seitz** [precice/tutorials#353]
Testing on the System Level poses the problem of having some results to compare against. 
In order to keep everything reproducible and have an overview we should introduce a machine readable file to pin down all the versions of components used to generate the reference results.

**Comment by MakisH** [comment]
We also wanted to get a machine-readable description of the preCICE Distribution, for which I would make a separate repository with some YAML or JSON files, and references to the respective Git submodules.

We could then use that repository to get the target reference versions, and have a PR update the references with every distribution update.

cc @uekerman

**Comment by MakisH** [comment]
Closed by #363.
