### ISSUE TITLE
Automatically delete any previous test `runs/` directories

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#356]
Currently, running the system tests manually generates a `runs/` directory. When running the tests again, the tests complain.

I suggest removing this directory automatically if it already exists, or alternatively having time-stamped subdirectories.

The directory should also be specified in the `.gitignore` file.

**Comment by valentin-seitz** [comment]
I Think for the Github Action its necessary to have it not automatically removed. So i would prefer the timestamp option.

**Comment by MakisH** [comment]
Closed by #358.
