### ISSUE TITLE
Compatibility of Nutils cases with preCICE v3

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#369]
Already ported:

- [channel-transport](https://github.com/precice/tutorials/tree/develop/channel-transport)
- [volume-coupled-flow](https://github.com/precice/tutorials/tree/develop/volume-coupled-flow)

Still missing:

- [x] flow-over-heated-plate
- [x] partitioned-heat-conduction
- [x] partitioned-heat-conduction-direct
- [x] perpendicular-flap

I will work on this.

**Comment by BenjaminRodenberg** [comment]
@MakisH Can we close this issue?
