### ISSUE TITLE
Enforce consistency among tutorials 

### ISSUE THREAD

**Issue by shkodm** [precice/tutorials#37]
It would be nice to enforce particular structure of tutorials, so new system tests based on tutorials can be added easier and overall orientation around tutorials made simpler. For instance: 
- Have different directories for input of different solvers with suitable names ( this is mostly done everywhere, apart from SU2-Calculix (see #36  ) )
- Have separate directories with the output of different solvers 
- Have convention about the structure of the `precice-config` files. For instance consistent order of attributes in the `m2n` tag, so that it is easier to parse (for instance to change exchange directory when running with docker ).

**Comment by MakisH** [comment]
This is related to #28.

**Comment by MakisH** [comment]
I think that, apart from the parts represented in #28 (and maybe specific issues such as #86, #87, #88), we have done quite some progress here.

Since this is also currently a bit vague, I am closing it to favor breaking down the problem to individual, easily-evaluated issues.
