### ISSUE TITLE
Tutorial partitioned-backwards-facing-step diverges when substeps > 0

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#373]
- Tutorials state (last commit / release): 0cd624ed5
- Operating system (e.g. Linux distribution and version): _Ubuntu 22.04_
- preCICE Version: develop f42e6c5c
- OpenFOAM adapter branch `fix-writing`, commit `7f316de6`
- OpenFOAM v2306

As discussed in https://github.com/precice/openfoam-adapter/pull/305#issuecomment-1717790734 and later, the [partitioned backwards facing step tutorial](https://precice.org/tutorials-partitioned-backwards-facing-step.html) diverges with the default value of `substeps`.

See the [precice-config.xml](https://github.com/precice/tutorials/blob/0cd624ed5dd7baafedd7784883063cfdbdc2f39c/partitioned-backwards-facing-step/precice-config.xml).

As @davidscn observed, setting `<exchange ... substeps="0" />` everywhere seems to give the right results.

In my view, this suggests that either:

- preCICE gives the wrong results with the default value (@BenjaminRodenberg any clue?)
- The OpenFOAM adapter does something wrong

Related to https://github.com/precice/openfoam-adapter/pull/305 and https://github.com/precice/openfoam-adapter/issues/303

**Comment by BenjaminRodenberg** [comment]
Note that quasi-Newton schemes currently do not support subcycling. A corresponding error is on the way (https://github.com/precice/precice/pull/1721). If the case is somehow doable with constant underrelaxation, you can use subcycling. This would be an important piece of information.

**Comment by uekerman** [comment]
We also changed the default to `substeps="false"` now.
https://github.com/precice/precice/pull/1732

**Comment by MakisH** [comment]
This tutorial now works with preCICE and tutorials from develop.
If I set `substeps=true`, I do get a helpful error message in the second participant.
