### ISSUE TITLE
Partitioned heat conduction: Crash, if max-time >= 2.0. Why?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/tutorials#385]
@NiklasVin and I observed that the `partitioned-heat-conduction` crashes with `ERROR:  Attempting to add a zero vector to the quasi-Newton V matrix. This means that the residuals in two consecutive iterations are identical. If a relative convergence limit was selected, consider increasing the convergence threshold.`, for the following changes in the configuration:

* `max-time` >= 2.0
* `time-window-size` <= 0.05

It looks to me like the problem is triggered, if we perform (roughly) 15 time windows or more. One possible work-around is to reduce the number of `time-windows-reused` in the acceleration scheme.

What's particularly interesting here: We already observed similar problems, that could be fixed by increasing the number of DoF (https://github.com/precice/precice/issues/1610). This fix, however, does not help here.

I don't think that this is a regression, because I was also able to reproduce the effect using the preCICE v2 software stack.

### Some ideas

1) Swapping first and second participant and applying acceleration to `Heat-Flux` works:

```diff
   <coupling-scheme:serial-implicit>
-    <participants first="Dirichlet" second="Neumann" />
+    <participants first="Neumann" second="Dirichlet" />
     <max-time value="1.0" />
-    <time-window-size value="0.1" />
+    <time-window-size value="0.05" />
     <max-iterations value="100" />
     <exchange data="Heat-Flux" mesh="Dirichlet-Mesh" from="Dirichlet" to="Neumann" />
     <exchange
@@ -50,10 +50,10 @@
       from="Neumann"
       to="Dirichlet"
       initialize="true" />
-    <relative-convergence-measure data="Heat-Flux" mesh="Dirichlet-Mesh" limit="1e-5" />
-    <relative-convergence-measure data="Temperature" mesh="Neumann-Mesh" limit="1e-5" />
+    <relative-convergence-measure data="Heat-Flux" mesh="Dirichlet-Mesh" limit="1e-10" />
+    <relative-convergence-measure data="Temperature" mesh="Neumann-Mesh" limit="1e-10" />
     <acceleration:IQN-ILS>
-      <data name="Temperature" mesh="Neumann-Mesh" />
+      <data name="Heat-Flux" mesh="Dirichlet-Mesh" />
       <initial-relaxation value="0.1" />
       <max-used-iterations value="10" />
       <time-windows-reused value="5" />
```

2) Modify the manufactured solution to use a time-dependent flux (+ some tweaking of convergence limits and resolution) also works:

```diff
--- a/partitioned-heat-conduction/fenics/heat.py
+++ b/partitioned-heat-conduction/fenics/heat.py
@@ -84,12 +84,12 @@ V_g = VectorFunctionSpace(mesh, 'P', 1)
 W = V_g.sub(0).collapse()
 
 # Define boundary conditions
-u_D = Expression('1 + x[0]*x[0] + alpha*x[1]*x[1] + beta*t', degree=2, alpha=alpha, beta=beta, t=0)
+u_D = Expression('1 + x[0]*x[0]*t + alpha*x[1]*x[1] + beta*t', degree=2, alpha=alpha, beta=beta, t=0)
 u_D_function = interpolate(u_D, V)
 
 if problem is ProblemType.DIRICHLET:
     # Define flux in x direction
-    f_N = Expression("2 * x[0]", degree=1, alpha=alpha, t=0)
+    f_N = Expression("2 * x[0] * t", degree=1, alpha=alpha, t=0)
     f_N_function = interpolate(f_N, W)
 
 # Define initial value
@@ -115,7 +115,7 @@ dt.assign(np.min([fenics_dt, precice_dt]))
 # Define variational problem
 u = TrialFunction(V)
 v = TestFunction(V)
-f = Expression('beta - 2 - 2*alpha', degree=2, alpha=alpha, beta=beta, t=0)
+f = Expression('beta + x[0] * x[0] - 2*t - 2*alpha', degree=2, alpha=alpha, beta=beta, t=0)
 F = u * v / dt * dx + dot(grad(u), grad(v)) * dx - (u_n / dt + f) * v * dx
 
 bcs = [DirichletBC(V, u_D, remaining_boundary)]
diff --git a/partitioned-heat-conduction/fenics/problem_setup.py b/partitioned-heat-conduction/fenics/problem_setup.py
index ff2996f..57694cc 100644
--- a/partitioned-heat-conduction/fenics/problem_setup.py
+++ b/partitioned-heat-conduction/fenics/problem_setup.py
@@ -33,7 +33,7 @@ class StraightBoundary(SubDomain):
 
 
 def get_geometry(domain_part):
-    nx = ny = 11
+    nx = ny = 20
 
     if domain_part is DomainPart.LEFT:
         p0 = Point(x_left, y_bottom)
diff --git a/partitioned-heat-conduction/precice-config.xml b/partitioned-heat-conduction/precice-config.xml
index 3b20fad..170be12 100644
--- a/partitioned-heat-conduction/precice-config.xml
+++ b/partitioned-heat-conduction/precice-config.xml
@@ -41,7 +41,7 @@
   <coupling-scheme:serial-implicit>
     <participants first="Dirichlet" second="Neumann" />
     <max-time value="1.0" />
-    <time-window-size value="0.1" />
+    <time-window-size value="0.05" />
     <max-iterations value="100" />
     <exchange data="Heat-Flux" mesh="Dirichlet-Mesh" from="Dirichlet" to="Neumann" />
     <exchange
@@ -50,8 +50,8 @@
       from="Neumann"
       to="Dirichlet"
       initialize="true" />
-    <relative-convergence-measure data="Heat-Flux" mesh="Dirichlet-Mesh" limit="1e-5" />
-    <relative-convergence-measure data="Temperature" mesh="Neumann-Mesh" limit="1e-5" />
+    <relative-convergence-measure data="Heat-Flux" mesh="Dirichlet-Mesh" limit="1e-7" />
+    <relative-convergence-measure data="Temperature" mesh="Neumann-Mesh" limit="1e-7" />
     <acceleration:IQN-ILS>
       <data name="Temperature" mesh="Neumann-Mesh" />
       <initial-relaxation value="0.1" />
```

**Comment by uekerman** [comment]
The failing case is a steady-state solution, right?
Then,

> This means that the residuals in two consecutive iterations are identical.

can very well happen once you are converging.

Of course, usability could be better.

**Comment by BenjaminRodenberg** [comment]
@uekerman it's a time-dependent case: $u = 1 + x^2 + \alpha y^2 + \beta t$ (even without modifications as suggested further down in the issue)

**Comment by uekerman** [comment]
Could you attach the iterations and convergence file of the failing case?

**Comment by BenjaminRodenberg** [comment]
Here you are.
[precice-Neumann-iterations.log](https://github.com/precice/tutorials/files/13039972/precice-Neumann-iterations.log)
[precice-Neumann-convergence.log](https://github.com/precice/tutorials/files/13039974/precice-Neumann-convergence.log)
[precice-Dirichlet-iterations.log](https://github.com/precice/tutorials/files/13039975/precice-Dirichlet-iterations.log)
[precice-Dirichlet-convergence.log](https://github.com/precice/tutorials/files/13039976/precice-Dirichlet-convergence.log)

Case is identical to 3ad45426b892c60209d9ac149c198cb238d12159 except the time step size:
```diff
diff --git a/partitioned-heat-conduction/precice-config.xml b/partitioned-heat-conduction/precice-config.xml
index 3b20fad..2027e19 100644
--- a/partitioned-heat-conduction/precice-config.xml
+++ b/partitioned-heat-conduction/precice-config.xml
@@ -41,7 +41,7 @@
   <coupling-scheme:serial-implicit>
     <participants first="Dirichlet" second="Neumann" />
     <max-time value="1.0" />
-    <time-window-size value="0.1" />
+    <time-window-size value="0.05" />
     <max-iterations value="100" />
     <exchange data="Heat-Flux" mesh="Dirichlet-Mesh" from="Dirichlet" to="Neumann" />
     <exchange
```

**Comment by BenjaminRodenberg** [comment]
Update: I decided to comment out the [`PRECICE_CHECK`](https://github.com/precice/precice/blob/37a8111670971986fca96604cf93b60e7a8b8668/src/acceleration/BaseQNAcceleration.cpp#L226-L229) that causes the crash. I do not observe clear problems w.r.t iteration count of the quasi-Newton acceleration or overall numerical error of the solution. For context: I'm currently performing convergence studies with this case.

Might be good to open a corresponding issue in `precice/precice`, since this looks to me like a problem with the quasi-Newton scheme that we should understand better.

**Comment by uekerman** [comment]
Without doing a close look, my best guess would be that the `CHECK` should be replaced by a "do not add the column and move on", maybe documented by a warning or info output.
I guess that this is anyway what happens in @BenjaminRodenberg commented-out version as then the filter removes the column again.

There are many connected issues in preCICE already:
- https://github.com/precice/precice/issues/1496
- https://github.com/precice/precice/issues/1107
- ...

**Comment by BenjaminRodenberg** [comment]
> Without doing a close look, my best guess would be that the `CHECK` should be replaced by a "do not add the column and move on", maybe documented by a warning or info output.
> I guess that this is anyway what happens in @BenjaminRodenberg commented-out version as then the filter removes the column again.

If the solution is that simple: Could we do this and even backport it to 2.5.1 for a bugfix release? Currently I have to patch 2.5.0 to perform some experiments and having a 2.5.1 release would simplify things.
