### ISSUE TITLE
`git checkout develop` fails with quota limit

### ISSUE THREAD

**Issue by cheriimoya** [precice/tutorials#389]
- Tutorials state (last commit / release): latest master (0482e5b4d3e1604dd031d2b113a2aaa63733c9a8), trying to switch to latest develop (6992f0dad9364f0f1648b86901d1ce32dbcf0577)
- Versions of solvers and adapters used: not relevant
- preCICE version: not relevant
- Log files: none

Hi there, I am trying to checkout the develop branch of this repo and I always get the same quota error:

```
tutorials/tutorials (master) $ git checkout develop                                                                                                                                                               
Updating files: 100% (265/265), done.
Downloading flow-over-heated-plate/reference-data/fluid-openfoam_solid-fenics.tar.gz (778 KB)
Error downloading object: flow-over-heated-plate/reference-data/fluid-openfoam_solid-fenics.tar.gz (2565ffc): Smudge error: Error downloading flow-over-heated-plate/reference-data/fluid-openfoam_solid-fenics.tar.gz (2565ffc51c8d80fab06ccdda33f62efceb6cdc03318998f5adc9ed0ac84acac2): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to '/home/.../tutorials/tutorials/.git/lfs/logs/20231106T192609.541845605.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: flow-over-heated-plate/reference-data/fluid-openfoam_solid-fenics.tar.gz: smudge filter lfs failed
[1]    2219159 exit 128   git checkout develop
```

Can this somehow be circumvented? Maybe by adding a mirror somewhere?

**Comment by MakisH** [comment]
Hi @cheriimoya,

can you try [cloning without Git LFS](https://stackoverflow.com/a/42021818/2254346)? You probably don't need any of the LFS objects.

We are currently working on integrating system tests into the tutorials repository, which means we also need to store the reference results somewhere. We went with Git LFS, but then we started hitting the bandwidth quota limits. We now have a solution, but the quota won't be reset before Nov 12.

@valentin-seitz I had not considered this side-effect: It is not only our system tests that clone the repository, but also users (and potentially other CI systems). We need to somehow disable it by default, or really find another solution.

**Comment by uekerman** [comment]
This should resolved now, right? @cheriimoya Could you confirm?

**Comment by cheriimoya** [comment]
Yes, now it works and i can checkout any branch:)
