### ISSUE TITLE
Parallel FEniCS test case fails

### ISSUE THREAD

**Issue by ajaust** [precice/tutorials#39]
Hi,

I tried to run the parallel FEniCS test case. However, when building the adapter I ran into issues (see https://github.com/precice/fenics-adapter/issues/39). I got the adapter to compile (I think at least), but now run into an error when running the test case.

I call
```
mpirun -n 2 python3 heat.py -d : -np 2 python3 heat.py -n
```
and get the following error message:
```
Traceback (most recent call last):
  File "heat.py", line 161, in <module>
    interpolation_strategy = fenicsadapter.core.ExactInterpolationExpression
AttributeError: module 'fenicsadapter.core' has no attribute 'ExactInterpolationExpression'
Traceback (most recent call last):
  File "heat.py", line 161, in <module>
    interpolation_strategy = fenicsadapter.core.ExactInterpolationExpression
AttributeError: module 'fenicsadapter.core' has no attribute 'ExactInterpolationExpression'
Traceback (most recent call last):
  File "heat.py", line 161, in <module>
    interpolation_strategy = fenicsadapter.core.ExactInterpolationExpression
AttributeError: module 'fenicsadapter.core' has no attribute 'ExactInterpolationExpression'
Traceback (most recent call last):
  File "heat.py", line 161, in <module>
    interpolation_strategy = fenicsadapter.core.ExactInterpolationExpression
AttributeError: module 'fenicsadapter.core' has no attribute 'ExactInterpolationExpression'
```

Does this mean that I did not properly compile the adapter or is there something else wrong?

Best,
Alex

**Comment by ajaust** [comment]
So... I was able to figure out something more.

I went back to the master branch
```bash
git checkout master
git pull
```
I rebuilt the adapter and now the error message that I had before disappeared. The tutorial `HT/partitioned-heat/fenics-fenics` works. However, the parallel example in the branch `parallelFenics` seems to use an older `fenicsadapter` interface. The parallel example is importing the adapter as
```python
import fenicsadapter.core
```
while the non-parallel example does
```python
from fenicsadapter import Adapter, ExactInterpolationExpression, GeneralInterpolationExpression
```

Now the parallel example fails with
```bash
mpirun -np 1 python3 heat.py -d
/home/jaustar/.local/lib/python3.6/site-packages/fenicsadapter/fenicsadapter.py:16: Warning: This version of the precice bindings is deprecated and will be removed in preCICE version 2.0.0. You may import the updated python module using "import precice_future as precice" instead. Refer to the changelog for more information.
  import precice
Traceback (most recent call last):
  File "heat.py", line 33, in <module>
    import fenicsadapter.core
ModuleNotFoundError: No module named 'fenicsadapter.core'
```

I checked the source code and came to the conclusion that the adapter in `master` is only suitable for serial runs. Now, I removed the `fenicsadapter`, checked out the `parallelFenics` branch of the tutorial and the adapter and end up with 

```/home/jaustar/.local/lib/python3.6/site-packages/fenicsadapter/core.py:14: Warning: This version of the precice bindings is deprecated and will be removed in preCICE version 2.0.0. You may import the updated python module using "import precice_future as precice" instead. Refer to the changelog for more information.
  import precice
Traceback (most recent call last):
  File "heat.py", line 161, in <module>
    interpolation_strategy = fenicsadapter.core.ExactInterpolationExpression
AttributeError: module 'fenicsadapter.core' has no attribute 'ExactInterpolationExpression'
```
again. I checked `core.py` (see [here](https://github.com/precice/fenics-adapter/blob/parallelFEniCS/fenicsadapter/core.py)) and there is no class called `ExactInterpolationExpression`. This class (and also `GeneralInterpolationExpression`) only exist in the serial adapter in the main branch.

**Comment by IshaanDesai** [comment]
The parallel functionality in `fenics-adapter` is being developed from scratch based on the new design. The current state of this implementation is in this PR: https://github.com/precice/fenics-adapter/pull/71
With this new proposed implementation the `HT/partitioned-heat/fenics-fenics` test case will work directly.

**Comment by IshaanDesai** [comment]
The parallel FEniCS case for the partitioned heat conduction tutorial is now working [in this state](https://github.com/precice/tutorials/tree/0c3407a553c5df6414fe114585db253626128b7b/partitioned-heat-conduction/fenics).
