### ISSUE TITLE
sys command from pre-compiled cgx waiting for user input

### ISSUE THREAD

**Issue by martinsaravia** [precice/tutorials#43]
For the OF-Calculix tutorial flap_perp it happens that if we download the pre-compiled cgx from Calculix page, the binary is precompiled with the flag ALLOW_SYS_FLAG   0; therefore, it requires user input for executing the system commands (this is so to avoid a catastrophe if the fbd file is evil) and therefore the execution of the solid stage is paused indefinitely. I think it could be useful to make clear in the tutorials that to accept the execution of every future 'sys'
command it necessary to add "ALLOW_SYS" in the .cgx file in the $HOME directory.

**Comment by MakisH** [comment]
This is related to #35. Providing the preconfigured case would solve this issue.

**Comment by fsimonis** [comment]
> To prevent the user from executing potential dangerous 'sys' commands the
> program will stop at every 'sys' command and waits for the user to either
> accept each single one or to accept the execution of every future 'sys'
> command by writing "ALLOW_SYS" in the .cgx file in the $HOME directory.
>
> If this functionallity is not desired then change "ALLOW_SYS_FLAG   0" in the
> cgx.h file to "ALLOW_SYS_FLAG   1". The program accepts then all 'sys' commands
> w/o warnings.

From the [cgx install docs](http://www.dhondt.de/cgx_2.16.INSTALL)

**Comment by MakisH** [comment]
@martinsaravia thank you very much for reporting this issue. I added a note in the tutorial pages linking to this issue.
