### ISSUE TITLE
Convert Nutils CHT tutorial to use precice_future

### ISSUE THREAD

**Issue by uekerman** [precice/tutorials#44]
The code: https://github.com/precice/tutorials/blob/master/CHT/flow-over-plate/buoyantPimpleFoam-nutils/Nutils/cht.py

The new bindings: https://github.com/precice/precice/tree/develop/src/precice/bindings/python_future

**Comment by MakisH** [comment]
This seems to be irrelevant since preCICE v2.

**Comment by uekerman** [comment]
Has been solved in https://github.com/precice/tutorials/commit/21ca911340b9248fc4ae74985be8933eb2b4315f
