### ISSUE TITLE
Flow-over-heated-plate-two-meshes: Different thickness of each domain

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#455]
I am not sure if there was some technical reason we had to do this like this (e.g., surface area of the interface), but this currently looks strange and makes visualization complicated:

![Screenshot from 2024-01-31 19-48-08](https://github.com/precice/tutorials/assets/4943683/94108a7d-8409-472c-8556-7164c6419e8f)

edit: originally observed in https://github.com/precice/tutorials/pull/271#issuecomment-1210179681

**Comment by uekerman** [comment]
Can't remember or imagine a technical reason. I guess it is simply a bug.
