### ISSUE TITLE
Heat-exchanger-simplified giving slightly different results when running in parallel

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#456]
Discovered in the context of https://github.com/precice/precice/pull/1914#issuecomment-1919099949. Copying here:

This transient tutorial uses a multi-implicit coupling scheme.

{fluid-top-openfoam, solid-calculix, fluid-bottom-openfoam}

### Serial

✅ Serial case works and the results look like the ones in the [tutorial](https://precice.org/tutorials-heat-exchanger-simplified.html).

![Screenshot from 2024-01-31 14-01-54](https://github.com/precice/precice/assets/4943683/125a6f59-ca90-4a91-86a5-50c00367f40d)

### Parallel

✅ Parallel (fluid-top-openfoam:2, solid-calculix:1, fluid-bottom-openfoam:2) completes.

:warning: The results are slightly different than the serial case, but I don't have any reference. I assume this has nothing to do with preCICE itself.

![Screenshot from 2024-01-31 15-48-23](https://github.com/precice/precice/assets/4943683/a010f5ae-ea10-4459-81d6-231c0c6d73ba)

**Comment by davidscn** [comment]
From your description, it's not clear how you observed the differences, how large the differences are and which quantities you inspected. Which domain decomposition did you use? Are the differences maybe within the solver tolerances?

**Comment by MakisH** [comment]
I missed copying over the second picture from the original post. Is it clear now?

I have used the default decomposition and every other configuration of the tutorial:

https://github.com/precice/tutorials/tree/60a97948b864fdc1d76fcc6a3093ac37d132e1d9/heat-exchanger-simplified

**Comment by MakisH** [comment]
Then let's keep it as it is. We changed too many things in the past year, it could be anything, and we don't have any validated reference here.
