### ISSUE TITLE
Perpendicular-flap solid-nutils case cannot start first (interruption signal)

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#457]
Discovered in the context of https://github.com/precice/precice/pull/1914#issuecomment-1919099949 Copying here:

{fluid-openfoam:1, solid-nutils:1} fails consistently with some network error if I first start Nutils and then OpenFOAM.

```
Successfully installed appdirs-1.4.4 bottombar-2.0.2 mpi4py-3.1.5 numpy-1.26.3 nutils-8.0 nutils-poly-1.0.0 psutil-5.9.8 pyprecice-3.0.0.0.dev2 stringly-1.0b3 treelog-1.0 typing-extensions-4.9.0
arguments > young=4000000.0
arguments > density=3000.0
arguments > poisson=0.3
arguments > nelems=2
arguments > solver_dt=0.01
arguments > npoints_per_elem=3
start 2024-01-31 17:20:45
optimize > constrained 6/126 dofs
optimize > optimum value 0.00e+00
optimize > optimum value 0.00e+00
---[precice]  This is preCICE version 3.0.0
---[precice]  Revision info: v2.5.0-604-g150d4ee8
---[precice]  Build type: Debug
---[precice]  Configuring preCICE with configuration "../precice-config.xml"
---[precice]  I am participant "Solid"
---[precice]  Setting up primary communication to coupling partner/s
---[precice] ERROR:  Accepting a socket connection at 127.0.0.1:41725 failed with the system error: accept: Interrupted system call
```

:warning: **UPDATE:** It looks like this only works if I first start OpenFOAM (first participant) and then Nutils (second participant). Previously, I was starting Nutils first.

- I consistently reproduce this on my system: starting with Nutils breaks, starting with OpenFOAM works
- I cannot replicate this issue with OpenFOAM-CalculiX of the same tutorial
- I cannot replicate this issue with OpenFOAM-Nutils in the channel-transport
- I cannot replicate this issue with the Python solverdummies.
- I do get the same error if I try to (indeed) interrupt Nutils during initialization. But why does this always happen for me in the perpendicular-flap?
- @IshaanDesai reproduced this.

**Comment by MakisH** [comment]
Related to `bottombar`, a dependency of Nutils. We need to adapt the `requirements.txt`.

https://github.com/precice/tutorials/pull/431#pullrequestreview-1812711006

**Comment by uekerman** [comment]
I do not completely get the purpose of this issue. It is a known problem in preCICE, https://github.com/precice/precice/issues/1443, and a workaround was implemented in Nutils. It has nothing to do with the tutorial.
Also documented [on the website](https://precice.org/website-testing/adapter-nutils.html) and no longer any problem with Nutils 8.5.

**Comment by uekerman** [comment]
> We need to adapt the requirements.txt

https://github.com/precice/tutorials/blob/60a97948b864fdc1d76fcc6a3093ac37d132e1d9/perpendicular-flap/solid-nutils/requirements.txt#L1

Should already do the job as it should install Nutils v8.5.

**Comment by MakisH** [comment]
> I do not completely get the purpose of this issue. It is a known problem in preCICE, [precice/precice#1443](https://github.com/precice/precice/issues/1443), and a workaround was implemented in Nutils. It has nothing to do with the tutorial. Also documented [on the website](https://precice.org/website-testing/adapter-nutils.html) and no longer any problem with Nutils 8.5.

It has something to do with the tutorial now that we are specifying a `requirements.txt` for it, so it can be solved (with a workaround) in this repository, by requiring `Nutils >= 8.5`.

While I looked at https://github.com/precice/precice/issues/1443 yesterday, it was not immediately clear to me that it was a manifestation of the same issue. Hopefully, this issue helps discover the full picture.

> > We need to adapt the requirements.txt
> 
> https://github.com/precice/tutorials/blob/60a97948b864fdc1d76fcc6a3093ac37d132e1d9/perpendicular-flap/solid-nutils/requirements.txt#L1
> 
> Should already do the job as it should install Nutils v8.5.

Unless I have already installed an earlier Nutils v8.x, or for any other reason the user ends up installing another v8.x.

Since it does fail with earlier v8.x, it is clear to me that the tutorial depends on v8.5 or later, and this should be encoded in the `requirements.txt`.

**Comment by MakisH** [comment]
Fixed in https://github.com/precice/tutorials/pull/462
