### ISSUE TITLE
Inconsistencies in structure of tutorials

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#461]
Follow-up of https://github.com/precice/tutorials/issues/228. The structure is documented in [the website](https://precice.org/community-contribute-to-precice.html#structure-of-a-tutorial) and clarified in https://github.com/precice/precice.github.io/pull/331.

The following tutorials need updates:

- oscillator @uekerman 
  - [x] python
  - [x] fmi
- partitioned-heat-conduction
  - [x] fenics: https://github.com/precice/tutorials/pull/459
  - [x] fenicsx (move from develop to branch) @IshaanDesai 
  - [x] nutils ~~@uekerman~~ @IshaanDesai https://github.com/precice/tutorials/pull/496
- partitioned-heat-conduction-complex
  - [x] fenics
- partitioned-heat-conduction-direct ~~@uekerman~~ @Fujikawas
  - [x] nutils
- volume-coupled-diffusion @BenjaminRodenberg 
  - [x] fenics https://github.com/precice/tutorials/pull/489

I would still consider the `aste-turbine` to be a very special case that is not meant to be extended or repeated in other tutorials.

Please comment regarding which cases you would like to port. No need to port every tutorial at once, but let's try to have a consistent structure until the next release of the tutorials.

**Comment by BenjaminRodenberg** [comment]
I don't want to prioritize this before my thesis is submitted or at least close to submission. I think this is also something that could be easily done by a research assistant and not urgent.

**Comment by MakisH** [comment]
You mean that you don't want to work on it, or that you don't want that the structure changes?

**Comment by BenjaminRodenberg** [comment]
I'm fine with the structural changes and we can also implement them rather sooner than later, but I don't have time to do it myself now.

If I stumble across a point where I can briefly do it anyway, I will do it occasionally (e.g. https://github.com/precice/tutorials/commit/459ab90fd803de85a5c370430a11693277d70c83).

**Comment by MakisH** [comment]
Thank you, I can also take over work packages on this.
