### ISSUE TITLE
perpendicular-flap

### ISSUE THREAD

**Issue by ShahramKa** [precice/tutorials#469]
Hi 

Running the perpendicular-flap using solid4foam and openfoam2012, I received this error for both the solid and fluid parts. 

---[precice] ERROR:  The configuration contains an unknown tag <solver-interface>. Expected tags are log, mesh, participant, profiling.
Looking for any time directories without results (e.g. stray functionObjectProperties files, see openfoam-adapter issue #26 on GitHub)...
-->

- Tutorials state (last commit / release):
- Versions of solvers and adapters used:OpenFoam2012, OpenFOAM-preCICE adapter - v1.2.3 + unreleased changes
- preCICE version: 3.0.0;no-info [git failed to run];PRECICE_FEATURE_MPI_COMMUNICATION=Y;PRECICE_FEATURE_PETSC_MAPPING=Y;PRECICE_FEATURE_GINKGO_MAPPING=N;PRECICE_FEATURE_PYTHON_ACTIONS=Y;PRECICE_BINDINGS_C=Y;PRECICE_BINDINGS_FORTRAN=Y;CXX=GNU;CXXFLAGS= -O3 -DNDEBUG;LDFLAGS=
- Log files:

Thank you

**Comment by uekerman** [comment]
There has not yet been a v3-compatible release of the tutorials and the OpenFOAM-preCICE adapter. Your options:

- Use preCICE v2.5.1 or
- Use the `develop` branches of the tutorials and the OpenFOAM-preCICE adapter or
- Wait till the new distribution will be released

More information in the blog post: 

https://precice.discourse.group/t/precice-v3-0-0-is-finally-out/1781
