### ISSUE TITLE
FSI SU2-CalculiX tutorial: geometry specifications and files

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#5]
I extracted the geometry specifications after visualizing the SU2 results, however it would be good to also have the geometry files and instructions somewhere. If a user is not familiar with SU2 or CalculiX but is developing a case using a different solver, they could use this as a starting point.

Note that the tutorial should not start from producing the meshes, but the user should be able to do this if needed. I think this would accelerate the development of other scenarios or adapters.

Todo:

- [ ] Update the geometry image: the flap is not at the center, it would be good to have dimensions and units.
- [ ] Upload the source geometry files or point to configuration files.
- [ ] Write some short instructions on producing the mesh from the geometry.

**Comment by IshaanDesai** [comment]
The specification of the case can be found [here](https://precice.org/tutorials-perpendicular-flap.html#setup)

**Comment by MakisH** [comment]
@IshaanDesai do we now also have the geometry files there? This was part of this issue. I just don't understand if the case is complete, but I guess we don't really need to add such steps anymore.

**Comment by IshaanDesai** [comment]
We dont have the geometry source files there but just the resulting meshed geometries. We can provide the source files and also the instructions on how to set up the case but this will be pure solver knowledge. It is an expectation that the user of the tutorial has some basic knowledge of the solvers. If users still have solver specific questions we can try to help or point them to other documentation. Is this a reasonable argument to not provide geometry specification and files?

**Comment by MakisH** [comment]
I guess anyway this is an issue that we cannot really fix and it goes to a different direction than we now want to go with this repository. If somebody in the future wants to directly contribute, please just contribute and refer to this issue.
