### ISSUE TITLE
Cannot reproduce reference results for elastic-tube-1d fluid_cpp - solid_python

### ISSUE THREAD

**Issue by fsimonis** [precice/tutorials#503]
What I run locally:

precice v3.0.0 `cmake --preset=production-audit`
pyprecice  3.0.0.0 (fresh install in venv)
tutorials da7a1494f5c36b4ef509daf2a43bfee42fb32d9d (current develop)

Case `elastic-tube-1d` with additional `<export:vtk directory="../precice-exports" />`.

For fluid-cpp:
```
rm -r build
./clean
./run
```

For solid-python:
```
./clean
python -m venv venv
. ./venv/bin/activate
pip install pyprecice
./run.sh
```

When comparing to the reference results:

## default fieldcompare tolerances

Solid-Nodes-Mesh-Solid.init.vtk fails

```
Reading 'precice-exports/Solid-Nodes-Mesh-Solid.init.vtk'
Reading '/home/simonis/Downloads/testo/reference-results-unpacked/fluid-cpp_solid-python/Solid-Nodes-Mesh-Solid.init.vtk'
 -- Comparing the field 'Rank': PASSED
 -- Comparing the field 'CrossSectionLength': PASSED
 -- Comparing the field 'Pressure': FAILED
   -- Report: Deviation above tolerance detected -> [1014.2157883686058] vs. [1014.2157883686283] ([2.22e-12] %)
   -- Predicate: DefaultEquality (abs_tol: 0., rel_tol: dynamic (last used: 2.220446049250313e-16))
```

Fluid-Nodes-Mesh-Fluid.dt1.vtk fails (init is fine)

```
Reading 'precice-exports/Fluid-Nodes-Mesh-Fluid.dt1.vtk'
Reading '/home/simonis/Downloads/testo/reference-results-unpacked/fluid-cpp_solid-python/Fluid-Nodes-Mesh-Fluid.dt1.vtk'
 -- Comparing the field 'Rank': PASSED
 -- Comparing the field 'CrossSectionLength': FAILED
   -- Report: Deviation above tolerance detected -> [1.0098272775377362] vs. [1.0098272775377328] ([3.30e-13] %)
   -- Predicate: DefaultEquality (abs_tol: 0., rel_tol: dynamic (last used: 2.220446049250313e-16))
 -- Comparing the field 'Pressure': FAILED
   -- Report: Deviation above tolerance detected -> [86.45528381913881] vs. [86.45528381910724] ([3.65e-11] %)
   -- Predicate: DefaultEquality (abs_tol: 0., rel_tol: dynamic (last used: 2.220446049250313e-16))
```

## test tolerance rtol 3e-7 

Solid-Nodes-Mesh-Solid differs dt16

```
Reading 'precice-exports/Solid-Nodes-Mesh-Solid.dt16.vtk'
Reading '/home/simonis/Downloads/testo/reference-results-unpacked/fluid-cpp_solid-python/Solid-Nodes-Mesh-Solid.dt16.vtk'
 -- Comparing the field 'Rank': PASSED
 -- Comparing the field 'CrossSectionLength': PASSED
 -- Comparing the field 'Pressure': FAILED
   -- Report: Deviation above tolerance detected -> [-307.74253302351144] vs. [-307.7426385118782] ([-3.43e-05] %)
   -- Predicate: DefaultEquality (abs_tol: 0., rel_tol: 3.e-07)
```

Fluod-Nodes-Mesh-Fluid differs at dt10

```
Reading 'precice-exports/Fluid-Nodes-Mesh-Fluid.dt10.vtk'
Reading '/home/simonis/Downloads/testo/reference-results-unpacked/fluid-cpp_solid-python/Fluid-Nodes-Mesh-Fluid.dt10.vtk'
 -- Comparing the field 'Rank': PASSED
 -- Comparing the field 'CrossSectionLength': PASSED
 -- Comparing the field 'Pressure': FAILED
   -- Report: Deviation above tolerance detected -> [-0.3854809932619241] vs. [-0.3854799683649429] ([-0.00] %)
   -- Predicate: DefaultEquality (abs_tol: 0., rel_tol: 3.e-07)
```

[Full output of the fieldcompare](https://github.com/precice/tutorials/files/14787154/fieldcompare.log)

**Comment by MakisH** [comment]
Sounds like an instance of https://github.com/precice/tutorials/issues/393

**Comment by fsimonis** [comment]
I opened a more detailed issue in https://github.com/precice/precice/issues/1984.

An interesting observation, which is probably worth checking even before getting into `fieldcompare` is that the iterations differ in both cases.

**Comment by MakisH** [comment]
Alright, so I wait for the bug investigation in preCICE before looking deeper into this from the perspective of the system tests.

**Comment by MakisH** [comment]
Well, every system is expected to give a bit different results, hence the selection of the tolerance is important.

Reference results are generated on the GitHub runners with this workflow: https://github.com/precice/tutorials/actions/workflows/generate_reference_results_manual.yml

**Comment by MakisH** [comment]
I understand that this issue has two parts:

- the "getting different results between v3.0.0 and develop" has been addressed in https://github.com/precice/precice/issues/1984
- the "getting different results locally than on GitHub runners" is partially not an issue, partially covered by #393.

Closing as duplicate.
