### ISSUE TITLE
Conversion errors in FEniCS FSI cases

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#504]
I cannot run the following cases/solvers (anymore):

- [`perpendicular-flap/solid-fenics/solid.py`](https://github.com/precice/tutorials/blob/da7a1494f5c36b4ef509daf2a43bfee42fb32d9d/perpendicular-flap/solid-fenics/solid.py)
- [`elastic-tube-3d/solid-fenics/solid.py`](https://github.com/precice/tutorials/blob/da7a1494f5c36b4ef509daf2a43bfee42fb32d9d/elastic-tube-3d/solid-fenics/solid.py)

While I can successfully run:

- [`flow-over-heated-plate/solid-fenics/solid.py`](https://github.com/precice/tutorials/blob/da7a1494f5c36b4ef509daf2a43bfee42fb32d9d/flow-over-heated-plate/solid-fenics/solid.py)
- [`partitioned-heat-conduction/solver-fenics/heat.py`](https://github.com/precice/tutorials/blob/da7a1494f5c36b4ef509daf2a43bfee42fb32d9d/partitioned-heat-conduction/solver-fenics/heat.py)

The solver starts, but at the time it tries to ?read? a checkpoint, the following happens:

```
---[precice]  iteration: 1 of 30 (min 1), time-window: 1 of 100, time: 0, time-window-size: 0.0001, max-time-step-size: 0.0001, ongoing: yes, time-window-complete: no, write-iteration-checkpoint 
Traceback (most recent call last):
  File "/home/gc/repos/precice/tutorials/elastic-tube-3d/solid-fenics/solid.py", line 158, in <module>
    res = m(avg(a_n, a_np1, alpha_m), v) + k(avg(u_n, du, alpha_f), v)
  File "/home/gc/repos/precice/tutorials/elastic-tube-3d/solid-fenics/solid.py", line 101, in k
    return inner(sigma(u), sym(grad(v))) * dx
  File "/home/gc/repos/precice/tutorials/elastic-tube-3d/solid-fenics/solid.py", line 91, in sigma
    return lambda_ * nabla_div(u) * Identity(dim) + 2 * mu * epsilon(u)
  File "/home/gc/.local/lib/python3.10/site-packages/ufl/operators.py", line 391, in nabla_div
    f = as_ufl(f)
  File "/home/gc/.local/lib/python3.10/site-packages/ufl/constantvalue.py", line 501, in as_ufl
    raise ValueError(
ValueError: Invalid type conversion: ({ A | A_{i_{20}} = f_21[i_{20}] * f_34 }) + ({ A | A_{i_{21}} = v_1[i_{21}] * (1 + -1 * f_34) }) can not be converted to any UFL type.
---[precice]  Implicitly finalizing in destructor
---[precice] ERROR:  The required actions write-iteration-checkpoint are not fulfilled. Did you forget to call "requiresReadingCheckpoint()" or "requiresWritingCheckpoint()"?
```

I have installed the following:

```shell
pip3 install --user fenics-ufl # Version: 2023.2.0
```

If I don't install `fenics-ufl`, it complains that it cannot find the package to import `nabla_div`.

I installed FEniCS from the official Ubuntu 22.04 PPA, as we also do in the [VM](https://github.com/precice/vm/blob/develop/provisioning/install-fenics.sh) and in the [FEniCS adapter CI](https://github.com/precice/fenics-adapter/blob/develop/tools/releasing/packaging/docker/Dockerfile).

- Tutorials state (last commit / release): da7a1494f5c36b4 (current develop)
- Versions of solvers and adapters used:
   - `python: import dolfin; dolifn.__version__` gives `'2019.2.0.13.dev0'`
   - `fenics-ufl` is 2023.2.0, same issue with `2019.1.0` and with `2022.2.0`. Available versions in PIP: `2017.1.0.post1, 2017.2.0, 2018.1.0, 2019.1.0, 2022.1.0.post0, 2022.2.0, 2023.1.0, 2023.1.1.post0, 2023.2.0`
- preCICE version: v3.1.0 release candidate (`v3.0.0-77-g3a1e77ea`)
- Log files:

**Comment by BenjaminRodenberg** [comment]
I can reproduce this problem on my system. Looks like there has been an update more or less recently. I ran this case without any issues in February and March when doing live demos in presentations. I might, of course, just have been lucky and running some outdated version of FEniCS or its dependencies without problems regarding `nabla_div`.

Replacing `nabla_div` and `nabla_grad` with `div` and `grad` seems to work. I'm not sure that this will result in exactly the same behavior, but this is something we will have to evaluate. I will push a PR with these changes and then we can continue working there.
