### ISSUE TITLE
Nutils tutorials always download pyprecice 3.0.0.0

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#530]
We currently set `pyprecice==3`.
We should probably set `pyprecice>=3,<4` or similar.

**Comment by fsimonis** [comment]
We can ask for a [compatible version `pyprecice~=3.0`](https://packaging.python.org/en/latest/specifications/version-specifiers/#compatible-release)

**Comment by BenjaminRodenberg** [comment]
What's holding us back? I just reviewed #541 and was also a bit surprised about the `pyprecice==3`. In #541 we will keep it consistent with the rest and merge now.

**Comment by MakisH** [comment]
> What's holding us back?

Nothing, just priorities and time.
I think the solution with `pyprecice~=3.0` is good, provided it will install a newer feature release, if available.

Happy to review PRs. :hugs:
