### ISSUE TITLE
Gradients: Surface-normal (scalars) vs complete (vector)

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#543]
In our tutorials and in the OpenFOAM adapter, we currently treat pressure gradient and velocity gradient as surface-normal gradients, and thus scalar fields. This already created some confusion in some discussion with @Fujikawas.

Isn't this a bit weird to assume that gradients are always surface-normal?

**Comment by uekerman** [comment]
What we actually have is the gradient times the normal vector. Maybe *flux* could be a better name?
