### ISSUE TITLE
FEniCS cases requirements.txt: fenics-dolfin not found

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#589]
Since https://github.com/precice/tutorials/pull/563, the FEniCS cases specify (for example, for the perpendicular-flap):

```
# Assuming FEniCS from ppa:fenics-packages/fenics was installed https://fenicsproject.org/download/archive/
# Use --system-site-packages in venv
fenics-dijitso==2019.2.0.dev0
fenics-dolfin==2019.2.0.13.dev0
fenics-ffc==2019.2.0.dev0
fenics-fiat==2019.2.0.dev0
fenics-ufl-legacy==2022.3.0
```

Trying to run the case (I admin I did not try that when I reviewed, as I wrote in the PR), I am getting:

```
Looking in indexes: https://pypi.org/simple, https://packagecloud.io/github/git-lfs/pypi/simple
ERROR: Could not find a version that satisfies the requirement fenics-dolfin==2019.2.0.13.dev0 (from versions: none)
ERROR: No matching distribution found for fenics-dolfin==2019.2.0.13.dev0
```

I recently ran the system tests a few times and this worked, though. It only recently started failing.

@NiklasVin @BenjaminRodenberg any clue what is going on here?

**Comment by BenjaminRodenberg** [comment]
Looks like there was an update of some FEniCS packages recently. See https://launchpad.net/~fenics-packages/+archive/ubuntu/fenics.

I updated the package locally and now I have:

```
$ pip show fenics-dolfin
WARNING: Skipping /usr/lib/python3.12/dist-packages/pybind11-2.11.1.dist-info due to invalid metadata entry 'name'
Name: fenics-dolfin
Version: 2019.2.0.64.dev0
Summary: DOLFIN Python interface
Home-page: 
Author: FEniCS Project
Author-email: 
License: 
Location: /usr/lib/python3/dist-packages
Requires: petsc4py
Required-by: 
```

Previously, the version was `2019.2.0.13.dev0`.

To make sure that this does not break again, I will use `~=2019.0` to specify any version compatible with `2019.0`. PR comes in a moment.
