### ISSUE TITLE
heat-exchaner: the mesh could be coarser (currently, downloading additional files is needed)

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#6]
Although this is a more complicated scenario and it would be complicated to provide specifications, it would be good to have geometry files somewhere.

For historical reasons, we don't have access to the source geometry files anymore. Reconstructing the geometry or adapting the tutorial to a known geometry would be useful, so that if anyone wants to change one of the solvers, they can do it.

Note that the tutorial should not start from producing the meshes, but the user should be able to do this.

Todo:
- [ ] Add some geometry files (reconstruct or adapt the tutorial)
- [ ] Add short instructions on how to produce the meshes.

**Comment by IshaanDesai** [comment]
Is this still relevant?

**Comment by MakisH** [comment]
That's mostly a question of what we want the tutorials to be. If we accept that the tutorials are only to see how things are implemented preCICE-wise, then no, this is not relevant anymore. But we still don't have geometry files and we start from a given mesh.

@DavidSCN do you maybe know if there are any tools in OpenFOAM to update a given mesh?

**Comment by IshaanDesai** [comment]
Also see [here](https://github.com/precice/tutorials/issues/5#issuecomment-819415930) as a relevant point in this discussion

**Comment by MakisH** [comment]
One additional argument here is that we currently share the complete meshes from LRZ Sync&Share, as they are several MB in size. If we added the mesh generation in the process (or if we managed to make the meshes coarser), we could host everything on GitHub and running would be much faster.

I would keep this issue open, as it affects the tutorials structure.

**Comment by MakisH** [comment]
Starting point for potentially coarsening an existing mesh: https://www.cfd-online.com/Forums/openfoam/98093-create-coarser-mesh-post-processing.html

We would then need something similar for CalculiX. Or, again, we remake the case from scratch (but that's a bigger package).

**Comment by DavidSCN** [comment]
> @DavidSCN do you maybe know if there are any tools in OpenFOAM to update a given mesh?

I don't understand what exactly to update, but I guess I'm not aware of anything in this direction.

**Comment by MakisH** [comment]
I added a note on the tutorial description to ask for help, pointing to this issue.

**Comment by MakisH** [comment]
I think we can now fix this since we have the simplified heat exchanger tutorial: #301

**Comment by jhdark** [comment]
Hi all, where can we download the results file (without having to run the whole case) for this HX tutorial? Thanks!

**Comment by MakisH** [comment]
Hi @jhdark,

there are no results published for the tutorial cases, but maybe we should think of a way to publish these properly together with software releases or at some point. The tutorials are mainly meant to be used as starting points to build upon them, not as validation cases.

You could get the results of the [flow-over-heated-plate tutorial](https://precice.org/tutorials-flow-over-heated-plate.html) from https://journal.openfoam.com/index.php/ofj/article/view/88, if that helps.

**Comment by jhdark** [comment]
How long does it typically take to run these tutorials? We are especially interested in the HX.

**Comment by MakisH** [comment]
Most of them should take a couple of minutes on an average laptop. The heat exchanger is an exception and one of the longest ones (would take an hour on my laptop). This is one of the first tutorials we got through some student project, and we do not have some of the original files to tune it further. It is also not very optimal in terms of features demonstrated.

Better start from the much newer https://precice.org/tutorials-heat-exchanger-simplified.html, instead.
