### ISSUE TITLE
Tutorial with CalculiX: instructions for visualization

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#7]
Todo:

- [ ] In the FSI with SU2 and CalculiX tutorial, information is missing on how to visualize the CalculiX results. I think that some short instructions would be useful.
- [ ] In the CHT with OpenFOAM and CalculiX tutorial, there is a short reference to use CGX or external tools. Some more elaborate instructions would be useful.

One could argue that a user should already know the solvers, but I think we can provide some first hints for users that want to use these as a starting point for a coupled simulation with other solvers.

**Comment by MakisH** [comment]
An alternative solution would be to use one of the CalculiX to VTK/ParaView converters. We don't need to focus on CGX, we only want a quick way to visualize the tutorials.

**Comment by Alphaoo1** [comment]
I regularly use [ccx2paraview](https://github.com/calculix/ccx2paraview), with `.vtu` option.
With the `.vtu` option you get a `.pvd` file, which has all the time steps in one file which makes it convenient to view the results in paraview.

**Comment by IshaanDesai** [comment]
The visualization instructions are now available [here](https://precice.org/tutorials-perpendicular-flap.html#post-processing)

**Comment by MakisH** [comment]
This was mainly meant to document some basic steps to get started with CGX. The `plot-displacement.sh` plots the preCICE watchpoint instead. Let's keep this open for a little longer, maybe I could write something short together with @KyleDavisSA.

**Comment by MakisH** [comment]
I added a few hints in https://github.com/precice/tutorials/commit/f05d14f4a82b75764ed5d372daed073c1fe387c2 at the perpendicular-flap case, to at least not completely forget of the existing tools. I hope that the community will gradually improve that page.
