### ISSUE TITLE
flow over plate tutorial's Fluid cases differ

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/tutorials#72]
* [Fluid folder for the OF-OF coupling](https://github.com/precice/openfoam-adapter/tree/master/tutorials/CHT/flow-over-plate/buoyantPimpleFoam-laplacianFoam/Fluid): folder is called `Fluid`. Participant is called [`Fluid`](https://github.com/precice/openfoam-adapter/blob/11db960fdfa0534eaeeb847b402ececa8a8bcb68/tutorials/CHT/flow-over-plate/buoyantPimpleFoam-laplacianFoam/Fluid/system/preciceDict#L12). `Allrun` script is provided in parent folder.
* Fluid folder for the [OF-FE](https://github.com/precice/tutorials/tree/develop/CHT/flow-over-plate/buoyantPimpleFoam-fenics) coupling does not exist, but has to be copied from [OF-OF case](https://github.com/precice/openfoam-adapter/tree/master/tutorials/CHT/flow-over-plate/buoyantPimpleFoam-laplacianFoam/Fluid): No `Allrun` or `runFluid` script is provided. User has to [manually start the case](https://github.com/precice/precice/wiki/Tutorial-for-CHT:-Flow-over-a-heated-plate-with-OpenFOAM-and-FEniCS#running).
* [Fluid folder for the OF-Nutils coupling](https://github.com/precice/tutorials/tree/develop/CHT/flow-over-plate/buoyantPimpleFoam-nutils/OpenFOAM): folder is called `OpenFOAM`. Participant is called [`OpenFOAM`](https://github.com/precice/tutorials/blob/f1c95f51c4b420345061045dbad612145e67f554/CHT/flow-over-plate/buoyantPimpleFoam-nutils/OpenFOAM/system/preciceDict#L12). `runFluid` script is provided in `OpenFOAM` folder.

This inconsistency leads to problems, if for the `OF-FE` case the user does not copy the `Fluid` folder from the `OF-OF` case (what we [suggest in the documentation](https://github.com/precice/precice/wiki/Tutorial-for-CHT:-Flow-over-a-heated-plate-with-OpenFOAM-and-FEniCS#get-the-openfoam-fluid-case)), but from the `OF-Nutils` case (which is available in the `tutorials`). 

Can we improve this situation by using the same structure for all cases? From my point of view the participant names should be consistent. Running via `Allrun` vs. `runFluid` vs. manually is not very critical, but could by achieved by changing the `Allrun` script to call independent `runFluid` and `runSolid` scripts.

Another solution would be to provide an independent `Fluid` folder in the `FE-FE` case. This will avoid mistakes, but I like it that the copy-paste approach currently very explicitly illustrates the idea of reusing an existing solver.

**Comment by MakisH** [comment]
This is (in my opinion) a duplicate of #28.

**Comment by BenjaminRueth** [comment]
> This is (in my opinion) a duplicate of #28.

100% correct. Then we should revive #28.
