### ISSUE TITLE
Inappropriate setup for FSI OpenFOAM tutorials

### ISSUE THREAD

**Issue by DavidSCN** [precice/tutorials#77]
During my work on precice/dealii-adapter#24, I struggled heavily with added mass instabilities. From the structural participant side, there is not really that much you can do to tackle this issue, since displacement and all its derivatives are zero in the beginning i.e. no inertia. 
Choosing a different setup (fvSchemes/fvSolutions) in the Fluid participant solves the issue (at least in my case), improves it in any case.

Since these are official tutorials, we should provide a good setup, especially considering the instabilities in FSI cases. Many users probably just copy these configurations and I think there have already been some discussions on discourse with users, facing similar problems.

**Comment by MakisH** [comment]
> Choosing a different setup (fvSchemes/fvSolutions) in the Fluid participant solves the issue (at least in my case), improves it in any case.

Could you describe this in more detail please? Pull Requests are, of course, very welcome.

**Comment by DavidSCN** [comment]
Depending on how @uekerman wants the `OpenFOAM-deal.II` tutorials, I guess there will be a PR anyway. We can not (completely) use the same cases for linear and nonlinear solver, since the coupled codes are in the precice-config, the OpenFOAM-precice-dict and the Solid-paramter file different (I finally got rid of the second mesh (faces) in the solid participant). Also, the nonlinear solver uses stresses (precice/openfoam-adapter#125).

**Comment by MakisH** [comment]
@DavidSCN I believe that this is now closed with the linked PRs, as part of https://github.com/orgs/precice/projects/5. Please reopen if needed.
