### ISSUE TITLE
Missing file in FSI/cylinderFlap/OpenFOAM-CalculiX ?

### ISSUE THREAD

**Issue by DamienGuenot** [precice/tutorials#81]
Hello,

I tried to run the FSI/cylinderFlap/OpenFOAM-CalculiX but an error occured for the Solid solver as a file is missing :
*ERROR in readinput: cannot open file Solid/all.msh

I cloned the git repository and I am wondering if I made a mistake or if it is really a missing file in the repo?

**Comment by MakisH** [comment]
Hi @DamienGuenot,

how are you running the tutorial?

Did you also [install and run CGX](https://github.com/precice/precice/wiki/Tutorial-for-FSI-with-OpenFOAM-and-CalculiX#step-1-install-required-software) first?

**Comment by DamienGuenot** [comment]
> Did you also [install and run CGX](https://github.com/precice/precice/wiki/Tutorial-for-FSI-with-OpenFOAM-and-CalculiX#step-1-install-required-software) first?

I saw it just few minutes ago.
It seems to be OK now.

Thank you.
