### ISSUE TITLE
FSI SU2/CalculiX: Restructure run scripts to remove tmux

### ISSUE THREAD

**Issue by MakisH** [precice/tutorials#89]
We are currently triggering tmux from inside the tutorial's run scripts, as e.g. here:
https://github.com/precice/tutorials/blob/master/FSI/flap_perp/SU2-CalculiX/runTutorial_parallel.sh

This is inconsistent with the rest of our cases and probably difficult for most new users to follow. We should restructure the tutorial to have a `runFluid` (also in parallel) and a `runSolid` script that can be started in separate terminals and are easier to follow.

We should also add an `Allrun` and an `Allclean` script, [currently missing](https://github.com/precice/tutorials/tree/master/FSI/flap_perp/SU2-CalculiX).

**Comment by IshaanDesai** [comment]
Closed in https://github.com/precice/tutorials/pull/100
