### ISSUE TITLE
Calculix OpenFoam Flow Coupling

### ISSUE THREAD

**Issue by DURAI04** [precice/tutorials#9]
Hi,
How to run a flow (compressible and in-compressible) problem using OpenFoam and Calculix. I need to run https://github.com/precice/precice/wiki/FSI-tutorial this example case using OpenFoam and Calculix.

It seems like CHT solver only available for openfoam & calculix coupling?

**Comment by MakisH** [comment]
Hi,

thank you for your question. This is not yet available in the OpenFOAM adapter, but we are actively working on it and it will be available in a few weeks. Keep an eye on [the respective issue](https://github.com/precice/openfoam-adapter/issues/7) for news.

Please post your questions on our [Gitter chatroom](https://gitter.im/precice/Lobby). We only use GitHub issues for code bugs and feature requests.

Best regards,
Makis
