### ISSUE TITLE
FSI SU2/CalculiX (flap_perp): CalculiX node ID#1 is fixed

### ISSUE THREAD

**Issue by vollmerb** [precice/tutorials#90]
I was working through the FSI SU2/CalculiX flap_perp tutorial and had trouble obtaining the correct results. Node ID1 in CalculiX is fixed and the flap.frd file shows zero displacement, with non-zero stress, strain and force for Node 1. This results in the simulation becoming unstable and failing after ~90 time steps. I checked the "fix1_beam.nam" and flap.inp file and Node 1 is only constrained in the symmetry plane (y-direction).

I found a workaround by changing the Node number in "all.msh" from 1 to 69. The element definition at the bottom of "all.msh" and the "interface_beam.nam" node number was also updated. These changes produced the expected deformation and the simulation was stable.

Why would Node 1 be fixed in the X/Z directions as well?

Setup:
Ubuntu 20.04
preCICE 2.0.2
ccx_2.16
SU2-6.0.0

**Comment by rumedimrak** [comment]
Hello @vollmerb. Can you share your updated mesh files? I also struggle with same issue.

**Comment by IshaanDesai** [comment]
The tutorial in its [new state here](https://github.com/precice/tutorials/tree/2e548cd7ad694965b1ad3f3695a28e057326478c/perpendicular-flap) works and has been verified. If the problem in the CalculiX mesh is seen again then please re-open this issue.
