### ISSUE TITLE
Improve documentation of FEniCS based tutorials

### ISSUE THREAD

**Issue by IshaanDesai** [precice/tutorials#96]
Consistently use [numpydoc docstring](https://numpydoc.readthedocs.io/en/latest/format.html) style for documentation of tutorial cases involving FEniCS:
- [ ]  [HT/partitioned-heat/fenics-fenics](https://github.com/precice/tutorials/tree/master/HT/partitioned-heat/fenics-fenics)
- [ ] [CHT/flow-over-plate/openfoam-fenics](https://github.com/precice/tutorials/tree/master/CHT/flow-over-plate/buoyantPimpleFoam-fenics)
- [ ] [FSI/cylinderFlap/openfoam-fenics](https://github.com/precice/tutorials/tree/master/FSI/cylinderFlap/OpenFOAM-FEniCS)
- [ ] [FSI/flap_perp/openfoam-fenics](https://github.com/precice/tutorials/tree/master/FSI/flap_perp/OpenFOAM-FEniCS)

Related issue in `fenics-adapter`: https://github.com/precice/fenics-adapter/issues/66

**Comment by BenjaminRodenberg** [comment]
Following a standard is generally useful. But do you think it's worth the effort for the tutorials? For the bindings and the adapter the documentation is important to use and understand the API. Here a standard is helpful.  `help(some_function)` is a killer feature and nice, if it gives consistent output. For the tutorials the documentation is mainly for understanding what the tutorial does. A standard is a nice to have here, but from my point of view we have with the same work a much lower impact. I don't see somebody typing `help(fenics_heat_errorcomputation)`, for example.

I see the following use cases for the tutorials:

1. developers: testing. CI does not care about comments. -> Comments are irrelevant
2. users: running tutorials. Look at results, but not at code/comments.  -> Comments are irrelevant
3. users/developers: understand what's going on in the code. Read code and comments.  -> Comments are relevant, but not sure is a standard is needed.
4. users/developers: use tutorial as a basis for your own research. -> Comments are relevant, if you extend the tutorial, you might even follow the standard. However: I'm not that optimistic that the first thing a user/developer in this situation will think is: "I have to write a comment. Let's follow the style of the project".

**Comment by IshaanDesai** [comment]
The arguments of not doing this are strong and hence this unnecessary work package is dropped.
