### ISSUE TITLE
code_aster - Openfpoam 7 coupling problem

### ISSUE THREAD

**Issue by DanielBorgesOliveira** [precice/tutorials#97]
Hi friends,

I have a problem running the code_aster + Openfoam example described in [https://github.com/precice/code_aster-adapter/wiki/Flow-over-plate-Code_Aster-Tutorial](here).
When I run the script **Allrun** in the folder **buoyantSimpleFoam-aster** the code_aster gets stuck in the task list consuming ~5% of the CPU.
The last line of the file **Solid.log**  shows this: `---[precice]  Setting up master communication to coupling partner/s`. You can get the file [https://mega.nz/file/949zwA5Y#GQmCST7OX63IrAd6AaymdJTcoPugzYpALcJQefdHJK0](here).

My setup is:
    Debian 10 amd64
    Openfoam V-7
    code_aster 14.4
    Precice v2.1.0
    Python Bindings v2.0.0.2rc2

What can I do to solve this?

Thank you very much.

**Comment by MakisH** [comment]
Hi @DanielBorgesOliveira,

could you please also upload your `Fluid.log` file? Are you using a [version of the adapter compatible with OpenFOAM 7](https://github.com/precice/openfoam-adapter/wiki/Notes-on-OpenFOAM)?

Please note that we prefer to discuss such questions on [our forum](https://precice.discourse.group/) first and document something here once it is a verified/specific problem. But thank you for reporting this already in any case! :smiley:

**Comment by DanielBorgesOliveira** [comment]
Hi @MakisH,

> could you please also upload your Fluid.log file?
Here is the Fluid.log: [https://mega.nz/file/lw9QzSLL#X_LyvBCGBgyIcUhLSYMGJTKSdLrca9VvLrPBxXyl9Zg](https://mega.nz/file/lw9QzSLL#X_LyvBCGBgyIcUhLSYMGJTKSdLrca9VvLrPBxXyl9Zg).

`Are you using a version of the adapter compatible with OpenFOAM 7?`
Yes. I checked out in the **OpenFOAM7** branch of the **openfoam-adapter**.


> Please note that we prefer to discuss such questions on our forum first and document something here once it is a verified/specific problem. But thank you for reporting this already in any case! smiley
Sorry, it will not happen again. Should I move the question to the forum or can we continue to discuss here?

Thank you very much.

**Comment by DanielBorgesOliveira** [comment]
Some advances here,

Looks like there was a problem with MFRONT linear solver in code_aster.
I recompiled the code_aster solver and this problem was solved.
Now I am facing another kind of problem.
Looks like the Fluid participant is running okay, but the Solid participant is encountering problems.

These are the Solid.log and Fluid.log:
[Solid.log](https://github.com/precice/tutorials/files/4992367/Solid.log)
[Fluid.log](https://github.com/precice/tutorials/files/4992368/Fluid.log)

**Comment by MakisH** [comment]
Actually, the fluid participant is not running ok:
```
--> FOAM Warning : 
    From function void* Foam::dlOpen(const Foam::fileName&, bool)
    in file POSIX.C at line 1251
    dlopen error : libpreciceAdapterFunctionObject.so: cannot open shared object file: No such file or directory
```
Unfortunately OpenFOAM only throws a warning and not an error in case there are problems with function objects. Have a look in the [troubleshooting section](https://github.com/precice/openfoam-adapter/wiki/Building#unknown-function-type-preciceadapterfunctionobject). Maybe this is the reason code_aster fails.

**Comment by DanielBorgesOliveira** [comment]
Thank you @MakisH,

After some investigation, I saw problems with openfoam-adapter compilation.
Here is the log: [wmake.log](https://github.com/precice/tutorials/files/4995619/wmake.log).

I think it is necessary to update the adapter code to reflect the new methods.
I think the problem [here](https://github.com/precice/python-bindings/issues/53) was similar.

**Comment by MakisH** [comment]
@DanielBorgesOliveira you are using preCICE v1.6.1 and [a few things changed in v2.0.0](https://github.com/precice/precice/wiki/Porting-adapters-from-preCICE-1.x-to-2.x). Please upgrade to the latest preCICE (currently v2.1.0) and everything should work.

I am closing this for now, but feel free to:
- Continue on [Discourse](https://precice.discourse.group/), if you still have such installation issues. For quick things, you can also ask on [Gitter](https://gitter.im/precice/Lobby).
- Reopen, if you still see the same issue on code_aster, but OpenFOAM runs well.

**Comment by DanielBorgesOliveira** [comment]
Problem solved. Thank you very much for your support and patience @MakisH.
